import { svelte } from "@sveltejs/vite-plugin-svelte";
import react from "@vitejs/plugin-react";
import fs from "node:fs/promises";
import path from "node:path";
import { defineConfig } from "vitest/config";
import type { BrowserCommand, ProjectConfig } from "vitest/node";
import { serveFontsLocally } from "../remote-react-components/dev/vitest/serveFontsLocally.ts";
import { vitestBrowserTestConfig } from "../core/src/index.ts";
import packageJson from "./package.json" with { type: "json" };

/*
 * The visual corpus of `remote-react-components`, run through both bindings.
 *
 * The 84 files are neither copied nor ported: they import their environment
 * from `@/tests/lib/environments`, and the alias below redirects exactly that
 * import to this package's harness — the same technique the cross-version
 * harness uses to run the same corpus against old published versions. Every
 * other `@/…` import still resolves inside `remote-react-components`, so the
 * scenarios, the helpers and the assets stay where they are.
 */
/*
 * The corpus runs with `remote-react-components` as the project root, not this
 * package. Its files address things from there — `userEvent.upload` takes the
 * literal path `src/tests/assets/gopher.webp`, and the setup file that serves
 * the fonts and registers `getByLocator` sits in its `dev/`. Only the harness
 * is pulled in from here, by absolute path through the alias.
 */
const reactPackage = path.resolve(
  import.meta.dirname,
  "../remote-react-components",
);

const reactPackageSrc = path.join(reactPackage, "src");

/*
 * `FileField` uploads with the literal path `src/tests/assets/gopher.webp`, and
 * vitest resolves it against the project root — which is this package. The
 * fixture is copied here rather than the root moved: see the note on `root`.
 */

const workspaceRoot = path.resolve(import.meta.dirname, "../..");

const corpusHarness = path.resolve(
  import.meta.dirname,
  "src/tests/corpus/environments.tsx",
);

/*
 * Regenerated by the reference run and never committed: the claim is "Svelte
 * renders what React renders today", which a stored baseline would quietly turn
 * into "what React rendered when someone last updated it".
 */
const referenceDir = path.resolve(import.meta.dirname, ".vitest-corpus");

const referenceFile = (key: string) =>
  path.join(referenceDir, `${key.replaceAll(/[^\w/.-]/g, "_")}.txt`);

const writeCorpusReference: BrowserCommand<
  [key: string, content: string]
> = async (ignoredContext, key, content) => {
  const file = referenceFile(key);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, content, "utf8");
};

const readCorpusReference: BrowserCommand<[key: string]> = async (
  ignoredContext,
  key,
) => {
  try {
    return await fs.readFile(referenceFile(key), "utf8");
  } catch {
    return null;
  }
};

/*
 * One browser, and the same one for both runs. The comparison is between the
 * two bindings, so anything else that differs — the theme each browser project
 * picks, its layout arithmetic — is noise the reference would carry.
 */
const corpusBrowser: ProjectConfig["browser"] = {
  ...vitestBrowserTestConfig.browser,
  commands: {
    ...vitestBrowserTestConfig.browser?.commands,
    serveFontsLocally,
    writeCorpusReference,
    readCorpusReference,
  },
  instances: [{ browser: "webkit", viewport: { width: 1280, height: 720 } }],
  screenshotFailures: false,
};

const corpusProject = (name: string, mode: "react" | "svelte") => ({
  /*
   * The root stays this package, although the tests live in the other one:
   * `svelte` is not resolvable from `remote-react-components`, so a run rooted
   * there ends up with two copies of the runtime and every `$effect` a harness
   * component creates lands outside the root `mount()` opened
   * (`effect_orphan`). The corpus is reached through `include` instead, and the
   * two things it addresses from its own root — the upload fixture and the
   * setup file — are handled below.
   */
  server: { fs: { allow: [workspaceRoot] } },
  optimizeDeps: { include: ["svelte", "@mittwald/**/*"] },
  plugins: [react(), svelte()],
  define: {
    __FLOW_CORPUS_MODE__: JSON.stringify(mode),
    __FLOW_REMOTE_SVELTE_COMPONENTS_PACKAGE_VERSION__: JSON.stringify(
      packageJson.version,
    ),
  },
  resolve: {
    dedupe: ["svelte"],
    alias: [
      { find: /^@\/tests\/lib\/environments$/, replacement: corpusHarness },
      { find: /^@\//, replacement: `${reactPackageSrc}/` },
    ],
  },
  test: {
    ...vitestBrowserTestConfig,
    browser: corpusBrowser,
    name,
    globals: true,
    include: [
      "../remote-react-components/src/tests/visual/**/*.browser.test.tsx",
    ],
    /*
     * The corpus's own setup, not this package's: it serves the fonts from the
     * repository (a hanging CDN request takes a whole run down, #3106) and
     * registers the `getByLocator` locator eighteen of the files use.
     */
    setupFiles: "../remote-react-components/dev/vitest/setupBrowser.ts",
    /*
     * The same budget the visual project runs with. A scenario renders,
     * interacts and snapshots, and the paint budget alone is 20s.
     */
    testTimeout: 60_000,
    fileParallelism: false,
    /*
     * One page for the whole run. Per-file isolation costs a fresh iframe per
     * file, and WebKit never frees a removed one (#3119).
     */
    isolate: false,
  },
});

export default defineConfig({
  test: {
    projects: [
      corpusProject("corpus-reference", "react"),
      corpusProject("corpus-svelte", "svelte"),
    ],
  },
});
