// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.
//
// Source: packages/codemods/src/composites/flowAlphaAll.ts
//
// jscodeshift downloads a `-t <url>` transform into the OS temp dir and
// requires it from there, so a transform served by URL cannot have relative
// imports. This is the composite above with its transforms inlined.

import type { Transform } from "jscodeshift";

/**
 * Moves the background value of `AccentBox` from `color` to `backgroundColor`
 * (alpha.786).
 *
 * `color` did not go away, it changed meaning: it used to set the background
 * (`"blue" | "green" | "gradient" | "neutral"`) and now sets the content color
 * (`"default" | "dark" | "light" | "dark-static" | "light-static"`). A blanket
 * rename would therefore break every element that already uses the new meaning.
 * The transform decides per value instead: a value from the new content-color
 * union stays on `color`, every other literal moves to `backgroundColor`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to
 * `AccentBox` — imported (named or as a namespace) from
 * `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components`, including their subpath entries —
 * are touched.
 *
 * Two cases are left alone, because both are undecidable without knowing the
 * value:
 *
 * - Dynamic values (`color={expression}`). The same expression means the
 *   background in old code and the content color in new code.
 * - An element that already carries `backgroundColor`. Moving `color` there would
 *   silently overwrite the explicit value.
 *
 * Both keep their `color` prop and need a look by hand.
 */
const flowAlphaAccentBoxColorToBackgroundColorTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set(["AccentBox"]);
  /** Values `color` still accepts — everything else was a background color. */
  const contentColors = new Set([
    "default",
    "dark",
    "light",
    "dark-static",
    "light-static",
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  /** The value of a string literal, or `undefined` for anything dynamic. */
  const literalValue = (node: unknown): string | undefined => {
    if (!node || typeof node !== "object" || !("type" in node)) {
      return undefined;
    }
    const { type } = node as { type: string };
    if (type !== "StringLiteral" && type !== "Literal") {
      return undefined;
    }
    const { value } = node as { value?: unknown };
    return typeof value === "string" ? value : undefined;
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    const attributes = path.node.attributes ?? [];

    const isNamed = (attribute: unknown, key: string): boolean =>
      !!attribute &&
      typeof attribute === "object" &&
      (attribute as { type?: string }).type === "JSXAttribute" &&
      (attribute as { name?: { type?: string; name?: string } }).name?.type ===
        "JSXIdentifier" &&
      (attribute as { name?: { name?: string } }).name?.name === key;

    // An explicit `backgroundColor` is the new API already — never overwrite it.
    if (attributes.some((attribute) => isNamed(attribute, "backgroundColor"))) {
      return;
    }

    for (const attribute of attributes) {
      if (!isNamed(attribute, "color") || attribute.type !== "JSXAttribute") {
        continue;
      }

      const value = attribute.value;

      // color="…" and color={"…"} — the only forms we can decide.
      const literal =
        literalValue(value) ??
        (value?.type === "JSXExpressionContainer"
          ? literalValue(value.expression)
          : undefined);

      if (literal === undefined || contentColors.has(literal)) {
        continue;
      }

      attribute.name = j.jsxIdentifier("backgroundColor");
    }
  });

  return root.toSource();
};

const flowAlphaAccentBoxColorToBackgroundColor =
  flowAlphaAccentBoxColorToBackgroundColorTransform;

/**
 * Renames the `action` prop to `onAction` on `Action`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to `Action`
 * — imported (named or as a namespace) from `@mittwald/flow-react-components`
 * or `@mittwald/flow-remote-react-components`, including their subpath entries
 * — are touched. Same-named components from other packages are left untouched,
 * and so is the `action` attribute of a plain `<form>`.
 *
 * An element that already carries `onAction` keeps it and only loses the stale
 * `action` prop, which mirrors what the runtime fallback does: an explicit
 * `onAction` wins.
 */
const flowAlphaActionPropToOnActionTransform: Transform = (fileInfo, { j }) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set(["Action"]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    const attributes = path.node.attributes ?? [];

    const isNamed = (attribute: (typeof attributes)[number], key: string) =>
      attribute.type === "JSXAttribute" &&
      attribute.name.type === "JSXIdentifier" &&
      attribute.name.name === key;

    const hasOnAction = attributes.some((attribute) =>
      isNamed(attribute, "onAction"),
    );

    if (hasOnAction) {
      path.node.attributes = attributes.filter(
        (attribute) => !isNamed(attribute, "action"),
      );
      return;
    }

    for (const attribute of attributes) {
      if (isNamed(attribute, "action") && attribute.type === "JSXAttribute") {
        attribute.name.name = "onAction";
      }
    }
  });

  return root.toSource();
};

const flowAlphaActionPropToOnAction = flowAlphaActionPropToOnActionTransform;

/**
 * Renames the `Align` component to `Combine`, and `AlignProps` to
 * `CombineProps`.
 *
 * Only names imported from `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components` (including their subpath entries)
 * are touched, so a same-named import from another package is left alone. An
 * `Align` imported under a local alias (`import { Align as Row }`) keeps its
 * alias — only the imported name changes. Namespace usages (`<Flow.Align />`,
 * `Flow.AlignProps`) are rewritten as well.
 */
const flowAlphaAlignToCombineTransform: Transform = (fileInfo, { j }) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const renames = new Map([
    ["Align", "Combine"],
    ["AlignProps", "CombineProps"],
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const root = j(fileInfo.source, { parser: "tsx" });

  /** Local identifiers that refer to a renamed export, mapped to the new name. */
  const localRenames = new Map<string, string>();
  /** Local names of `import * as Flow` namespace imports from a Flow package. */
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local?.name
        ) {
          flowNamespaces.add(String(specifier.local.name));
          continue;
        }

        if (
          specifier.type !== "ImportSpecifier" ||
          specifier.imported.type !== "Identifier"
        ) {
          continue;
        }

        const imported = specifier.imported.name;
        const renamed = renames.get(imported);
        if (!renamed) {
          continue;
        }

        // Mutate in place so an `import type` / `type X` modifier survives.
        const local = String(specifier.local?.name ?? imported);
        specifier.imported.name = renamed;
        if (local === imported) {
          localRenames.set(local, renamed);
          if (specifier.local) {
            specifier.local.name = renamed;
          }
        }
        // An aliased `Align as Row` keeps `Row` and needs no further change.
      }
    });

  if (localRenames.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  /**
   * `JSXIdentifier` extends `Identifier`, so this one pass covers JSX tags,
   * value references and type references alike. Positions where the name is not
   * a reference to the import — an object key, a member's property, a JSX
   * attribute name — are skipped.
   */
  root.find(j.Identifier).forEach((path) => {
    const parent = path.parent.node;

    const isNamespaceMember =
      (parent.type === "MemberExpression" ||
        parent.type === "JSXMemberExpression") &&
      parent.property === path.node;

    if (isNamespaceMember) {
      const object = parent.object;
      if (object.type === "Identifier" || object.type === "JSXIdentifier") {
        const renamed = renames.get(path.node.name);
        if (renamed && flowNamespaces.has(String(object.name))) {
          path.node.name = renamed;
        }
      }
      return;
    }

    if (
      parent.type === "ImportSpecifier" ||
      parent.type === "JSXAttribute" ||
      ((parent.type === "ObjectProperty" || parent.type === "Property") &&
        parent.key === path.node &&
        !parent.computed)
    ) {
      return;
    }

    const renamed = localRenames.get(path.node.name);
    if (renamed) {
      path.node.name = renamed;
    }
  });

  return root.toSource();
};

const flowAlphaAlignToCombine = flowAlphaAlignToCombineTransform;

/**
 * Renames the `color="accent"` prop value to `color="success"` on `Button` and
 * `SubmitButton`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to one of
 * those components — imported (named or as a namespace) from
 * `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components`, including their subpath entries —
 * are touched. Same-named components from other packages are left untouched.
 * Only the literal value `"accent"` is rewritten (`color="accent"` and
 * `color={"accent"}`); dynamic values such as `color={expr}` are skipped.
 */
const flowAlphaButtonColorAccentToSuccessTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set(["Button", "SubmitButton"]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const isAccentLiteral = (node: unknown): boolean => {
    if (!node || typeof node !== "object" || !("type" in node)) {
      return false;
    }
    const { type } = node as { type: string };
    return (
      (type === "StringLiteral" || type === "Literal") &&
      (node as { value?: unknown }).value === "accent"
    );
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    for (const attribute of path.node.attributes ?? []) {
      if (
        attribute.type !== "JSXAttribute" ||
        attribute.name.type !== "JSXIdentifier" ||
        attribute.name.name !== "color"
      ) {
        continue;
      }

      const value = attribute.value;

      // color="accent"
      if (isAccentLiteral(value)) {
        attribute.value = j.stringLiteral("success");
        continue;
      }

      // color={"accent"}
      if (
        value?.type === "JSXExpressionContainer" &&
        isAccentLiteral(value.expression)
      ) {
        value.expression = j.stringLiteral("success");
      }
    }
  });

  return root.toSource();
};

const flowAlphaButtonColorAccentToSuccess =
  flowAlphaButtonColorAccentToSuccessTransform;

/**
 * Renames the `color="primary"` prop value to `color="default"` on the five
 * components changed by the alpha.837 design update: `Breadcrumb`,
 * `HeaderNavigation`, `Heading`, `IllustratedMessage` and `Link`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to one of
 * those components — imported (named or as a namespace) from
 * `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components`, including their subpath entries —
 * are touched. Components that still accept `color="primary"` (e.g. `Button`)
 * and same-named elements from other packages (e.g. a router `Link`) are left
 * untouched. Only the literal value `"primary"` is rewritten (`color="primary"`
 * and `color={"primary"}`); dynamic values such as `color={expr}` are skipped.
 */
const flowAlphaColorPrimaryToDefaultTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set([
    "Breadcrumb",
    "HeaderNavigation",
    "Heading",
    "IllustratedMessage",
    "Link",
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const isPrimaryLiteral = (node: unknown): boolean => {
    if (!node || typeof node !== "object" || !("type" in node)) {
      return false;
    }
    const { type } = node as { type: string };
    return (
      (type === "StringLiteral" || type === "Literal") &&
      (node as { value?: unknown }).value === "primary"
    );
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    for (const attribute of path.node.attributes ?? []) {
      if (
        attribute.type !== "JSXAttribute" ||
        attribute.name.type !== "JSXIdentifier" ||
        attribute.name.name !== "color"
      ) {
        continue;
      }

      const value = attribute.value;

      // color="primary"
      if (isPrimaryLiteral(value)) {
        attribute.value = j.stringLiteral("default");
        continue;
      }

      // color={"primary"}
      if (
        value?.type === "JSXExpressionContainer" &&
        isPrimaryLiteral(value.expression)
      ) {
        value.expression = j.stringLiteral("default");
      }
    }
  });

  return root.toSource();
};

const flowAlphaColorPrimaryToDefault = flowAlphaColorPrimaryToDefaultTransform;

/**
 * Runs every `0.2.0-alpha` migration codemod in one pass, in the order the
 * changes were released. Use it to catch up from an older alpha in one go
 * instead of running the transforms one by one.
 *
 * Two transforms in this folder are deliberately **not** part of it:
 *
 * - `flowRemote` converts an app to `@mittwald/flow-remote-react-components`.
 *   That is a port to a different package, not a migration, and running it on a
 *   normal app would rewrite every Flow import.
 * - `flow020` migrates `0.1.0` to `0.2.0` by collapsing subpath imports onto the
 *   package root. Since then the package gained subpath entries it does not
 *   know about (`/internal`, `/flr-universal`, `/mittwald-password-tools-js`),
 *   so on a current codebase it would break those imports. Run it separately,
 *   and only when coming from `0.1.0`.
 */
const flowAlphaAllTransform: Transform = (fileInfo, api, options) => {
  /** Ordered by the release the respective change shipped in. */
  const transforms: Transform[] = [
    flowAlphaActionPropToOnAction, // alpha.646
    flowAlphaAccentBoxColorToBackgroundColor, // alpha.786
    flowAlphaColorPrimaryToDefault, // alpha.846
    flowAlphaButtonColorAccentToSuccess, // alpha.1046
    flowAlphaAlignToCombine, // alpha.1047
  ];

  let source = fileInfo.source;

  for (const transform of transforms) {
    // A transform returns the unchanged source, or nothing at all, when it does
    // not apply — both mean "keep what we have" and must not end the chain.
    const result = transform({ ...fileInfo, source }, api, options);
    if (typeof result === "string") {
      source = result;
    }
  }

  return source;
};

export default flowAlphaAllTransform;
