// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.
//
// Source: packages/codemods/src/composites/flow1.ts
//
// jscodeshift downloads a `-t <url>` transform into the OS temp dir and
// requires it from there, so a transform served by URL cannot have relative
// imports. This is the composite above with its transforms inlined.

import type { Transform } from "jscodeshift";

/**
 * Moves the background value of `AccentBox` from `color` to `backgroundColor`
 * (alpha.786).
 *
 * `color` did not go away, it changed meaning: it used to set the background
 * (`"blue" | "green" | "gradient" | "neutral"`) and now sets the content color
 * (`"default" | "dark" | "light" | "dark-static" | "light-static"`). A blanket
 * rename would therefore break every element that already uses the new meaning.
 * The transform decides per value instead: a value from the new content-color
 * union stays on `color`, every other literal moves to `backgroundColor`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to
 * `AccentBox` — imported (named or as a namespace) from
 * `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components`, including their subpath entries —
 * are touched.
 *
 * Two cases are left alone, because both are undecidable without knowing the
 * value:
 *
 * - Dynamic values (`color={expression}`). The same expression means the
 *   background in old code and the content color in new code.
 * - An element that already carries `backgroundColor`. Moving `color` there would
 *   silently overwrite the explicit value.
 *
 * Both keep their `color` prop and need a look by hand.
 */
const flowAlphaAccentBoxColorToBackgroundColorTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set(["AccentBox"]);
  /** Values `color` still accepts — everything else was a background color. */
  const contentColors = new Set([
    "default",
    "dark",
    "light",
    "dark-static",
    "light-static",
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  /** The value of a string literal, or `undefined` for anything dynamic. */
  const literalValue = (node: unknown): string | undefined => {
    if (!node || typeof node !== "object" || !("type" in node)) {
      return undefined;
    }
    const { type } = node as { type: string };
    if (type !== "StringLiteral" && type !== "Literal") {
      return undefined;
    }
    const { value } = node as { value?: unknown };
    return typeof value === "string" ? value : undefined;
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    const attributes = path.node.attributes ?? [];

    const isNamed = (attribute: unknown, key: string): boolean =>
      !!attribute &&
      typeof attribute === "object" &&
      (attribute as { type?: string }).type === "JSXAttribute" &&
      (attribute as { name?: { type?: string; name?: string } }).name?.type ===
        "JSXIdentifier" &&
      (attribute as { name?: { name?: string } }).name?.name === key;

    // An explicit `backgroundColor` is the new API already — never overwrite it.
    if (attributes.some((attribute) => isNamed(attribute, "backgroundColor"))) {
      return;
    }

    for (const attribute of attributes) {
      if (!isNamed(attribute, "color") || attribute.type !== "JSXAttribute") {
        continue;
      }

      const value = attribute.value;

      // color="…" and color={"…"} — the only forms we can decide.
      const literal =
        literalValue(value) ??
        (value?.type === "JSXExpressionContainer"
          ? literalValue(value.expression)
          : undefined);

      if (literal === undefined || contentColors.has(literal)) {
        continue;
      }

      attribute.name = j.jsxIdentifier("backgroundColor");
    }
  });

  return root.toSource();
};

const flowAlphaAccentBoxColorToBackgroundColor =
  flowAlphaAccentBoxColorToBackgroundColorTransform;

/**
 * Renames the `action` prop to `onAction` on `Action`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to `Action`
 * — imported (named or as a namespace) from `@mittwald/flow-react-components`
 * or `@mittwald/flow-remote-react-components`, including their subpath entries
 * — are touched. Same-named components from other packages are left untouched,
 * and so is the `action` attribute of a plain `<form>`.
 *
 * An element that already carries `onAction` keeps it and only loses the stale
 * `action` prop, which mirrors what the runtime fallback does: an explicit
 * `onAction` wins.
 */
const flowAlphaActionPropToOnActionTransform: Transform = (fileInfo, { j }) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set(["Action"]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    const attributes = path.node.attributes ?? [];

    const isNamed = (attribute: (typeof attributes)[number], key: string) =>
      attribute.type === "JSXAttribute" &&
      attribute.name.type === "JSXIdentifier" &&
      attribute.name.name === key;

    const hasOnAction = attributes.some((attribute) =>
      isNamed(attribute, "onAction"),
    );

    if (hasOnAction) {
      path.node.attributes = attributes.filter(
        (attribute) => !isNamed(attribute, "action"),
      );
      return;
    }

    for (const attribute of attributes) {
      if (isNamed(attribute, "action") && attribute.type === "JSXAttribute") {
        attribute.name.name = "onAction";
      }
    }
  });

  return root.toSource();
};

const flowAlphaActionPropToOnAction = flowAlphaActionPropToOnActionTransform;

/**
 * Replaces the removed `Button` props interfaces with `ButtonProps`
 * (alpha.646).
 *
 * `RemoteButtonElementProps`, `ResetButtonProps` and `SubmitButtonProps` were
 * removed; all three are `ButtonProps`. There is no alias for the old names, so
 * a codebase still using them does not compile.
 *
 * This is more than a rename, because the names do not share an entry.
 * `SubmitButtonProps` and `ResetButtonProps` came from the `react-hook-form`
 * entry, which does not export `ButtonProps` — renaming them in place would
 * swap one import error for another. The specifier therefore moves to the
 * package root of whichever Flow package it came from, joining an existing
 * import from that root or getting a new one.
 *
 * The scope is `@mittwald/flow-react-components` and its subpath entries only.
 * `@mittwald/flow-remote-react-components` exports no component prop types at
 * all, so there is nothing to move a remote import onto — a remote codebase has
 * to pick its own source for the type. `RemoteButtonElementProps` is left alone
 * for the same reason, and because `@mittwald/flow-remote-elements` still
 * exports that name today.
 *
 * A same-named import from another package is left alone. A name imported under
 * a local alias (`import { SubmitButtonProps as P }`) keeps its alias — it
 * becomes `ButtonProps as P`. Namespace usages (`Flow.SubmitButtonProps`) are
 * rewritten as well.
 *
 * All three collapse onto `ButtonProps`, so a file importing more than one of
 * them — or one of them next to `ButtonProps` itself — ends up with a single
 * specifier instead of a duplicate declaration, which would not parse.
 */
const flowAlphaButtonPropsInterfacesTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = ["@mittwald/flow-react-components"];
  const removed = new Set(["ResetButtonProps", "SubmitButtonProps"]);
  const newName = "ButtonProps";

  /** The Flow package a module specifier belongs to, or `undefined`. */
  const rootPackageOf = (source: string): string | undefined =>
    flowPackages.find((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  // ast-types models `importKind` on the declaration only, while babel also
  // puts it on the specifier — which is where a per-specifier `type X` lives.
  const isTypeOnly = (node: object): boolean =>
    (node as { importKind?: string }).importKind === "type";

  const root = j(fileInfo.source, { parser: "tsx" });

  /** Local identifiers that have to be renamed (no alias in play). */
  const localRenames = new Set<string>();
  /** Local names of `import * as Flow` namespace imports from a Flow package. */
  const flowNamespaces = new Set<string>();
  /** `package:local` pairs that already import `ButtonProps` from a root. */
  const bound = new Set<string>();
  /** `package:local` pairs that still need importing, and whether type-only. */
  const wanted = new Map<
    string,
    { pkg: string; local: string; type: boolean }
  >();

  const flowImports = root
    .find(j.ImportDeclaration)
    .filter((path) => !!rootPackageOf(String(path.node.source.value)));

  flowImports.forEach((path) => {
    const source = String(path.node.source.value);
    for (const specifier of path.node.specifiers ?? []) {
      if (
        specifier.type === "ImportNamespaceSpecifier" &&
        specifier.local?.name
      ) {
        flowNamespaces.add(String(specifier.local.name));
        continue;
      }

      if (
        specifier.type === "ImportSpecifier" &&
        specifier.imported.type === "Identifier" &&
        specifier.imported.name === newName &&
        source === rootPackageOf(source)
      ) {
        bound.add(`${source}:${String(specifier.local?.name ?? newName)}`);
      }
    }
  });

  flowImports.forEach((path) => {
    const source = String(path.node.source.value);
    const pkg = rootPackageOf(source) ?? source;
    const declarationIsType = isTypeOnly(path.node);
    const specifiers = path.node.specifiers ?? [];
    const survivors: typeof specifiers = [];

    for (const specifier of specifiers) {
      if (
        specifier.type !== "ImportSpecifier" ||
        specifier.imported.type !== "Identifier" ||
        !removed.has(specifier.imported.name)
      ) {
        survivors.push(specifier);
        continue;
      }

      const imported = specifier.imported.name;
      const local = String(specifier.local?.name ?? imported);
      const isAlias = local !== imported;
      const newLocal = isAlias ? local : newName;
      const key = `${pkg}:${newLocal}`;

      if (!isAlias) {
        localRenames.add(local);
      }

      if (!bound.has(key)) {
        const existing = wanted.get(key);
        const type = declarationIsType || isTypeOnly(specifier);
        wanted.set(key, {
          pkg,
          local: newLocal,
          // A value import must not lose out to a type-only one.
          type: existing ? existing.type && type : type,
        });
      }
    }

    if (survivors.length === specifiers.length) {
      return;
    }

    // Leaving an emptied declaration behind would turn it into a side-effect
    // import of an entry the file no longer uses.
    if (survivors.length === 0) {
      j(path).remove();
      return;
    }

    path.node.specifiers = survivors;
  });

  if (
    wanted.size === 0 &&
    localRenames.size === 0 &&
    flowNamespaces.size === 0
  ) {
    return fileInfo.source;
  }

  for (const { pkg, local, type } of wanted.values()) {
    const specifier = j.importSpecifier(
      j.identifier(newName),
      j.identifier(local),
    );

    // Join an import from the package root when the file already has one and
    // it can carry the specifier; otherwise add a declaration of its own.
    const host = root
      .find(j.ImportDeclaration)
      .filter(
        (path) =>
          String(path.node.source.value) === pkg &&
          isTypeOnly(path.node) === type,
      )
      .paths()[0];

    if (host) {
      host.node.specifiers = [...(host.node.specifiers ?? []), specifier];
      continue;
    }

    const declaration = j.importDeclaration([specifier], j.literal(pkg));
    if (type) {
      declaration.importKind = "type";
    }

    const firstImport = root.find(j.ImportDeclaration).paths()[0];
    if (firstImport) {
      j(firstImport).insertBefore(declaration);
    } else {
      root.get().node.program.body.unshift(declaration);
    }
  }

  /**
   * `JSXIdentifier` extends `Identifier`, so this one pass covers value
   * references and type references alike. Positions where the name is not a
   * reference to the import — an object key, a member's property, a JSX
   * attribute name — are skipped.
   */
  root.find(j.Identifier).forEach((path) => {
    const parent = path.parent.node;

    const isNamespaceMember =
      (parent.type === "MemberExpression" ||
        parent.type === "JSXMemberExpression") &&
      parent.property === path.node;

    if (isNamespaceMember) {
      const object = parent.object;
      if (
        (object.type === "Identifier" || object.type === "JSXIdentifier") &&
        removed.has(path.node.name) &&
        flowNamespaces.has(String(object.name))
      ) {
        path.node.name = newName;
      }
      return;
    }

    if (
      parent.type === "ImportSpecifier" ||
      parent.type === "JSXAttribute" ||
      ((parent.type === "ObjectProperty" || parent.type === "Property") &&
        parent.key === path.node &&
        !parent.computed)
    ) {
      return;
    }

    if (localRenames.has(path.node.name)) {
      path.node.name = newName;
    }
  });

  return root.toSource();
};

const flowAlphaButtonPropsInterfaces = flowAlphaButtonPropsInterfacesTransform;

/**
 * Renames `MutedActionError` to `AbortActionError`, along with its two static
 * helpers (alpha.712).
 *
 * ```diff
 * -throw new MutedActionError();
 * +throw new AbortActionError();
 * -MutedActionError.isMutedActionError(error);
 * +AbortActionError.isAbortActionError(error);
 * -MutedActionError.rethrowIfNotMuted(error);
 * +AbortActionError.rethrowIfNotAborted(error);
 * ```
 *
 * There is no alias for the old name, so a codebase still using it does not
 * compile.
 *
 * The thrown error's `name` changed too, so a `error.name ===
 * "MutedActionError"` comparison is rewritten as well — but only in a file that
 * imports the class, and only where the string is compared with `==`, `===`,
 * `!=` or `!==`. A check living in a file that never imports the class cannot
 * be recognised; grep for the string once when you are done.
 *
 * Only names imported from `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components` (including their subpath entries)
 * are touched. A local alias (`import { MutedActionError as Muted }`) keeps its
 * alias — the static helpers on it are renamed all the same. Namespace usages
 * (`Flow.MutedActionError`) are rewritten too.
 */
const flowAlphaMutedActionErrorToAbortActionErrorTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const oldName = "MutedActionError";
  const newName = "AbortActionError";
  const memberRenames = new Map([
    ["isMutedActionError", "isAbortActionError"],
    ["rethrowIfNotMuted", "rethrowIfNotAborted"],
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  // ast-types models `importKind` on the declaration only, while babel also
  // puts it on the specifier — which is where a per-specifier `type X` lives.
  const isTypeOnly = (specifier: object): boolean =>
    (specifier as { importKind?: string }).importKind === "type";
  const makeValueImport = (specifier: object): void => {
    (specifier as { importKind?: string }).importKind = "value";
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  /**
   * Local names bound to the class, alias or not — the static helpers hang off
   * these.
   */
  const classLocals = new Set<string>();
  /** Local names whose identifier itself has to be renamed (no alias in play). */
  const localRenames = new Set<string>();
  /** Local names of `import * as Flow` namespace imports from a Flow package. */
  const flowNamespaces = new Set<string>();

  const flowImports = root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)));

  /**
   * Local names the file already binds to the new name. Renaming onto one of
   * them must not add a second specifier, which would not parse.
   */
  const claimed = new Set<string>();

  flowImports.forEach((path) => {
    for (const specifier of path.node.specifiers ?? []) {
      if (
        specifier.type === "ImportNamespaceSpecifier" &&
        specifier.local?.name
      ) {
        flowNamespaces.add(String(specifier.local.name));
        continue;
      }

      if (
        specifier.type === "ImportSpecifier" &&
        specifier.imported.type === "Identifier" &&
        specifier.imported.name === newName
      ) {
        claimed.add(String(specifier.local?.name ?? newName));
      }
    }
  });

  flowImports.forEach((path) => {
    const specifiers = path.node.specifiers ?? [];
    const survivors: typeof specifiers = [];

    for (const specifier of specifiers) {
      if (
        specifier.type !== "ImportSpecifier" ||
        specifier.imported.type !== "Identifier" ||
        specifier.imported.name !== oldName
      ) {
        survivors.push(specifier);
        continue;
      }

      const local = String(specifier.local?.name ?? oldName);
      const isAlias = local !== oldName;
      const newLocal = isAlias ? local : newName;

      classLocals.add(local);
      if (!isAlias) {
        localRenames.add(local);
      }

      if (claimed.has(newLocal)) {
        // The name is already bound by another import — drop this specifier
        // instead of declaring it twice.
        if (!isTypeOnly(specifier)) {
          for (const kept of survivors) {
            if (
              kept.type === "ImportSpecifier" &&
              kept.imported.type === "Identifier" &&
              String(kept.local?.name ?? kept.imported.name) === newLocal
            ) {
              makeValueImport(kept);
            }
          }
        }
        continue;
      }
      claimed.add(newLocal);

      // Mutate in place so an `import type` / `type X` modifier survives.
      specifier.imported.name = newName;
      if (!isAlias && specifier.local) {
        specifier.local.name = newName;
      }
      survivors.push(specifier);
    }

    if (survivors.length === specifiers.length) {
      return;
    }

    // Leaving an emptied declaration behind would turn it into a side-effect
    // import of an entry the file no longer uses.
    if (survivors.length === 0) {
      j(path).remove();
      return;
    }

    path.node.specifiers = survivors;
  });

  if (classLocals.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  /** Does this expression denote the class — `Muted` or `Flow.MutedActionError`? */
  const isClassReference = (
    node:
      | {
          type: string;
          name?: unknown;
          object?: { type: string; name?: unknown } | null;
          property?: { type: string; name?: unknown } | null;
        }
      | null
      | undefined,
  ): boolean => {
    if (!node) {
      return false;
    }
    if (node.type === "Identifier") {
      return classLocals.has(String(node.name));
    }
    return (
      node.type === "MemberExpression" &&
      node.object?.type === "Identifier" &&
      flowNamespaces.has(String(node.object.name)) &&
      node.property?.type === "Identifier" &&
      String(node.property.name) === oldName
    );
  };

  // Static helpers first: the check reads the pre-rename object name.
  root.find(j.MemberExpression).forEach((path) => {
    const { object, property } = path.node;
    if (property.type !== "Identifier" || !isClassReference(object)) {
      return;
    }

    const renamed = memberRenames.get(property.name);
    if (renamed) {
      property.name = renamed;
    }
  });

  root.find(j.Identifier).forEach((path) => {
    const parent = path.parent.node;

    const isNamespaceMember =
      (parent.type === "MemberExpression" ||
        parent.type === "JSXMemberExpression") &&
      parent.property === path.node;

    if (isNamespaceMember) {
      const object = parent.object;
      if (
        (object.type === "Identifier" || object.type === "JSXIdentifier") &&
        path.node.name === oldName &&
        flowNamespaces.has(String(object.name))
      ) {
        path.node.name = newName;
      }
      return;
    }

    if (
      parent.type === "ImportSpecifier" ||
      parent.type === "JSXAttribute" ||
      ((parent.type === "ObjectProperty" || parent.type === "Property") &&
        parent.key === path.node &&
        !parent.computed)
    ) {
      return;
    }

    if (localRenames.has(path.node.name)) {
      path.node.name = newName;
    }
  });

  // `error.name === "MutedActionError"` — a comparison is the only place where
  // the string can be recognised as the error's name rather than free text.
  const comparisons = new Set(["===", "!==", "==", "!="]);
  root.find(j.BinaryExpression).forEach((path) => {
    if (!comparisons.has(path.node.operator)) {
      return;
    }

    for (const side of [path.node.left, path.node.right]) {
      if (
        (side.type === "StringLiteral" || side.type === "Literal") &&
        side.value === oldName
      ) {
        side.value = newName;
      }
    }
  });

  return root.toSource();
};

const flowAlphaMutedActionErrorToAbortActionError =
  flowAlphaMutedActionErrorToAbortActionErrorTransform;

/**
 * Replaces `AsyncRule` and `SyncRule` with `Rule` (alpha.802).
 *
 * `@mittwald/password-tools-js` merged both classes into a single abstract
 * `Rule`, and the `mittwald-password-tools-js` entry stopped re-exporting the
 * old names. A custom rule extends `Rule` and may return its result
 * synchronously or as a promise — the distinction the two classes encoded is
 * gone, so both names collapse onto the same one.
 *
 * Only names imported from the `mittwald-password-tools-js` entry are touched,
 * so a same-named import from another package is left alone. A name imported
 * under a local alias (`import { AsyncRule as Base }`) keeps its alias — only
 * the imported name changes. Namespace usages (`Pw.AsyncRule`) are rewritten as
 * well.
 *
 * Because both names collapse onto `Rule`, a file importing more than one of
 * them would end up with a duplicate specifier. Those collapse onto one.
 */
const flowAlphaPasswordToolsRuleTransform: Transform = (fileInfo, { j }) => {
  const flowPackages = [
    "@mittwald/flow-react-components/mittwald-password-tools-js",
    "@mittwald/flow-remote-react-components/mittwald-password-tools-js",
  ];
  const renames = new Map([
    ["AsyncRule", "Rule"],
    ["SyncRule", "Rule"],
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.includes(source);

  // ast-types models `importKind` on the declaration only, while babel also
  // puts it on the specifier — which is where a per-specifier `type X` lives.
  const isTypeOnly = (specifier: object): boolean =>
    (specifier as { importKind?: string }).importKind === "type";
  const makeValueImport = (specifier: object): void => {
    (specifier as { importKind?: string }).importKind = "value";
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  /** Local identifiers that refer to a renamed export, mapped to the new name. */
  const localRenames = new Map<string, string>();
  /**
   * Whether any import specifier was rewritten. An aliased `Align as Row` adds
   * nothing to `localRenames` — its local name stays `Row` — so counting those
   * alone would treat an alias-only file as untouched and discard the rewrite.
   */
  let renamedAnImport = false;
  /** Local names of `import * as Flow` namespace imports from a Flow package. */
  const flowNamespaces = new Set<string>();

  const flowImports = root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)));

  /**
   * `imported:local` pairs the file already binds without a rename. A rename
   * that lands on one of these must not add a second specifier for it — the
   * name is available from the import that already carries it, which is also
   * the entry that really exports it.
   */
  const claimed = new Set<string>();

  flowImports.forEach((path) => {
    for (const specifier of path.node.specifiers ?? []) {
      if (
        specifier.type === "ImportNamespaceSpecifier" &&
        specifier.local?.name
      ) {
        flowNamespaces.add(String(specifier.local.name));
        continue;
      }

      if (
        specifier.type !== "ImportSpecifier" ||
        specifier.imported.type !== "Identifier" ||
        renames.has(specifier.imported.name)
      ) {
        continue;
      }

      claimed.add(
        `${specifier.imported.name}:${String(
          specifier.local?.name ?? specifier.imported.name,
        )}`,
      );
    }
  });

  flowImports.forEach((path) => {
    const specifiers = path.node.specifiers ?? [];
    const survivors: typeof specifiers = [];

    for (const specifier of specifiers) {
      if (
        specifier.type !== "ImportSpecifier" ||
        specifier.imported.type !== "Identifier"
      ) {
        survivors.push(specifier);
        continue;
      }

      const imported = specifier.imported.name;
      const renamed = renames.get(imported);
      if (!renamed) {
        survivors.push(specifier);
        continue;
      }

      const local = String(specifier.local?.name ?? imported);
      const isAlias = local !== imported;
      const newLocal = isAlias ? local : renamed;
      const key = `${renamed}:${newLocal}`;

      renamedAnImport = true;
      if (!isAlias) {
        // An aliased import keeps its local name and needs no further change.
        localRenames.set(local, renamed);
      }

      // Renaming can collide with a name the file already binds — directly, or
      // because a second old name maps onto the same new one. Either way the
      // binding already exists, so this specifier goes away instead of
      // producing a duplicate declaration, which would not parse.
      const collision = claimed.has(key);
      claimed.add(key);
      if (collision) {
        // A value import must not lose out to a type-only one.
        if (!isTypeOnly(specifier)) {
          for (const kept of survivors) {
            if (
              kept.type === "ImportSpecifier" &&
              kept.imported.type === "Identifier" &&
              `${kept.imported.name}:${String(
                kept.local?.name ?? kept.imported.name,
              )}` === key
            ) {
              makeValueImport(kept);
            }
          }
        }
        continue;
      }

      // Mutate in place so an `import type` / `type X` modifier survives.
      specifier.imported.name = renamed;
      if (!isAlias && specifier.local) {
        specifier.local.name = renamed;
      }
      survivors.push(specifier);
    }

    if (survivors.length === specifiers.length) {
      return;
    }

    // Every specifier moved to an import that already binds the name. Leaving
    // the declaration behind would turn it into a side-effect import of an
    // entry the file no longer uses.
    if (survivors.length === 0) {
      j(path).remove();
      return;
    }

    path.node.specifiers = survivors;
  });

  if (!renamedAnImport && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  /**
   * `JSXIdentifier` extends `Identifier`, so this one pass covers JSX tags,
   * value references and type references alike. Positions where the name is not
   * a reference to the import — an object key, a member's property, a JSX
   * attribute name — are skipped.
   */
  root.find(j.Identifier).forEach((path) => {
    const parent = path.parent.node;

    const isNamespaceMember =
      (parent.type === "MemberExpression" ||
        parent.type === "JSXMemberExpression") &&
      parent.property === path.node;

    if (isNamespaceMember) {
      const object = parent.object;
      if (object.type === "Identifier" || object.type === "JSXIdentifier") {
        const renamed = renames.get(path.node.name);
        if (renamed && flowNamespaces.has(String(object.name))) {
          path.node.name = renamed;
        }
      }
      return;
    }

    if (
      parent.type === "ImportSpecifier" ||
      parent.type === "JSXAttribute" ||
      ((parent.type === "ObjectProperty" || parent.type === "Property") &&
        parent.key === path.node &&
        !parent.computed)
    ) {
      return;
    }

    const renamed = localRenames.get(path.node.name);
    if (renamed) {
      path.node.name = renamed;
    }
  });

  return root.toSource();
};

const flowAlphaPasswordToolsRule = flowAlphaPasswordToolsRuleTransform;

/**
 * Renames the `Align` component to `Combine`, and `AlignProps` to
 * `CombineProps`.
 *
 * Only names imported from `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components` (including their subpath entries)
 * are touched, so a same-named import from another package is left alone. An
 * `Align` imported under a local alias (`import { Align as Row }`) keeps its
 * alias — only the imported name changes. Namespace usages (`<Flow.Align />`,
 * `Flow.AlignProps`) are rewritten as well.
 */
const flowAlphaAlignToCombineTransform: Transform = (fileInfo, { j }) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const renames = new Map([
    ["Align", "Combine"],
    ["AlignProps", "CombineProps"],
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  // ast-types models `importKind` on the declaration only, while babel also
  // puts it on the specifier — which is where a per-specifier `type X` lives.
  const isTypeOnly = (specifier: object): boolean =>
    (specifier as { importKind?: string }).importKind === "type";
  const makeValueImport = (specifier: object): void => {
    (specifier as { importKind?: string }).importKind = "value";
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  /** Local identifiers that refer to a renamed export, mapped to the new name. */
  const localRenames = new Map<string, string>();
  /**
   * Whether any import specifier was rewritten. An aliased `Align as Row` adds
   * nothing to `localRenames` — its local name stays `Row` — so counting those
   * alone would treat an alias-only file as untouched and discard the rewrite.
   */
  let renamedAnImport = false;
  /** Local names of `import * as Flow` namespace imports from a Flow package. */
  const flowNamespaces = new Set<string>();

  const flowImports = root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)));

  /**
   * `imported:local` pairs the file already binds without a rename. A rename
   * that lands on one of these must not add a second specifier for it — the
   * name is available from the import that already carries it, which is also
   * the entry that really exports it.
   */
  const claimed = new Set<string>();

  flowImports.forEach((path) => {
    for (const specifier of path.node.specifiers ?? []) {
      if (
        specifier.type === "ImportNamespaceSpecifier" &&
        specifier.local?.name
      ) {
        flowNamespaces.add(String(specifier.local.name));
        continue;
      }

      if (
        specifier.type !== "ImportSpecifier" ||
        specifier.imported.type !== "Identifier" ||
        renames.has(specifier.imported.name)
      ) {
        continue;
      }

      claimed.add(
        `${specifier.imported.name}:${String(
          specifier.local?.name ?? specifier.imported.name,
        )}`,
      );
    }
  });

  flowImports.forEach((path) => {
    const specifiers = path.node.specifiers ?? [];
    const survivors: typeof specifiers = [];

    for (const specifier of specifiers) {
      if (
        specifier.type !== "ImportSpecifier" ||
        specifier.imported.type !== "Identifier"
      ) {
        survivors.push(specifier);
        continue;
      }

      const imported = specifier.imported.name;
      const renamed = renames.get(imported);
      if (!renamed) {
        survivors.push(specifier);
        continue;
      }

      const local = String(specifier.local?.name ?? imported);
      const isAlias = local !== imported;
      const newLocal = isAlias ? local : renamed;
      const key = `${renamed}:${newLocal}`;

      renamedAnImport = true;
      if (!isAlias) {
        // An aliased import keeps its local name and needs no further change.
        localRenames.set(local, renamed);
      }

      // Renaming can collide with a name the file already binds — directly, or
      // because a second old name maps onto the same new one. Either way the
      // binding already exists, so this specifier goes away instead of
      // producing a duplicate declaration, which would not parse.
      const collision = claimed.has(key);
      claimed.add(key);
      if (collision) {
        // A value import must not lose out to a type-only one.
        if (!isTypeOnly(specifier)) {
          for (const kept of survivors) {
            if (
              kept.type === "ImportSpecifier" &&
              kept.imported.type === "Identifier" &&
              `${kept.imported.name}:${String(
                kept.local?.name ?? kept.imported.name,
              )}` === key
            ) {
              makeValueImport(kept);
            }
          }
        }
        continue;
      }

      // Mutate in place so an `import type` / `type X` modifier survives.
      specifier.imported.name = renamed;
      if (!isAlias && specifier.local) {
        specifier.local.name = renamed;
      }
      survivors.push(specifier);
    }

    if (survivors.length === specifiers.length) {
      return;
    }

    // Every specifier moved to an import that already binds the name. Leaving
    // the declaration behind would turn it into a side-effect import of an
    // entry the file no longer uses.
    if (survivors.length === 0) {
      j(path).remove();
      return;
    }

    path.node.specifiers = survivors;
  });

  if (!renamedAnImport && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  /**
   * `JSXIdentifier` extends `Identifier`, so this one pass covers JSX tags,
   * value references and type references alike. Positions where the name is not
   * a reference to the import — an object key, a member's property, a JSX
   * attribute name — are skipped.
   */
  root.find(j.Identifier).forEach((path) => {
    const parent = path.parent.node;

    const isNamespaceMember =
      (parent.type === "MemberExpression" ||
        parent.type === "JSXMemberExpression") &&
      parent.property === path.node;

    if (isNamespaceMember) {
      const object = parent.object;
      if (object.type === "Identifier" || object.type === "JSXIdentifier") {
        const renamed = renames.get(path.node.name);
        if (renamed && flowNamespaces.has(String(object.name))) {
          path.node.name = renamed;
        }
      }
      return;
    }

    if (
      parent.type === "ImportSpecifier" ||
      parent.type === "JSXAttribute" ||
      ((parent.type === "ObjectProperty" || parent.type === "Property") &&
        parent.key === path.node &&
        !parent.computed)
    ) {
      return;
    }

    const renamed = localRenames.get(path.node.name);
    if (renamed) {
      path.node.name = renamed;
    }
  });

  return root.toSource();
};

const flowAlphaAlignToCombine = flowAlphaAlignToCombineTransform;

/**
 * Renames the `color="accent"` prop value to `color="success"` on `Button` and
 * `SubmitButton`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to one of
 * those components — imported (named or as a namespace) from
 * `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components`, including their subpath entries —
 * are touched. Same-named components from other packages are left untouched.
 * Only the literal value `"accent"` is rewritten (`color="accent"` and
 * `color={"accent"}`); dynamic values such as `color={expr}` are skipped.
 */
const flowAlphaButtonColorAccentToSuccessTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set(["Button", "SubmitButton"]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const isAccentLiteral = (node: unknown): boolean => {
    if (!node || typeof node !== "object" || !("type" in node)) {
      return false;
    }
    const { type } = node as { type: string };
    return (
      (type === "StringLiteral" || type === "Literal") &&
      (node as { value?: unknown }).value === "accent"
    );
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    for (const attribute of path.node.attributes ?? []) {
      if (
        attribute.type !== "JSXAttribute" ||
        attribute.name.type !== "JSXIdentifier" ||
        attribute.name.name !== "color"
      ) {
        continue;
      }

      const value = attribute.value;

      // color="accent"
      if (isAccentLiteral(value)) {
        attribute.value = j.stringLiteral("success");
        continue;
      }

      // color={"accent"}
      if (
        value?.type === "JSXExpressionContainer" &&
        isAccentLiteral(value.expression)
      ) {
        value.expression = j.stringLiteral("success");
      }
    }
  });

  return root.toSource();
};

const flowAlphaButtonColorAccentToSuccess =
  flowAlphaButtonColorAccentToSuccessTransform;

/**
 * Renames the `color="primary"` prop value to `color="default"` on the five
 * components changed by the alpha.837 design update: `Breadcrumb`,
 * `HeaderNavigation`, `Heading`, `IllustratedMessage` and `Link`.
 *
 * The scope is deliberately narrow. Only JSX elements that resolve to one of
 * those components — imported (named or as a namespace) from
 * `@mittwald/flow-react-components` or
 * `@mittwald/flow-remote-react-components`, including their subpath entries —
 * are touched. Components that still accept `color="primary"` (e.g. `Button`)
 * and same-named elements from other packages (e.g. a router `Link`) are left
 * untouched. Only the literal value `"primary"` is rewritten (`color="primary"`
 * and `color={"primary"}`); dynamic values such as `color={expr}` are skipped.
 */
const flowAlphaColorPrimaryToDefaultTransform: Transform = (
  fileInfo,
  { j },
) => {
  const flowPackages = [
    "@mittwald/flow-react-components",
    "@mittwald/flow-remote-react-components",
  ];
  const affectedComponents = new Set([
    "Breadcrumb",
    "HeaderNavigation",
    "Heading",
    "IllustratedMessage",
    "Link",
  ]);

  const isFlowImport = (source: string): boolean =>
    flowPackages.some((pkg) => source === pkg || source.startsWith(`${pkg}/`));

  const isPrimaryLiteral = (node: unknown): boolean => {
    if (!node || typeof node !== "object" || !("type" in node)) {
      return false;
    }
    const { type } = node as { type: string };
    return (
      (type === "StringLiteral" || type === "Literal") &&
      (node as { value?: unknown }).value === "primary"
    );
  };

  const root = j(fileInfo.source, { parser: "tsx" });

  // Local JSX identifier -> canonical component name (resolves `as` aliases).
  const localToComponent = new Map<string, string>();
  // Local names of `import * as Flow` namespace imports from a Flow package.
  const flowNamespaces = new Set<string>();

  root
    .find(j.ImportDeclaration)
    .filter((path) => isFlowImport(String(path.node.source.value)))
    .forEach((path) => {
      for (const specifier of path.node.specifiers ?? []) {
        if (
          specifier.type === "ImportSpecifier" &&
          specifier.imported.type === "Identifier" &&
          affectedComponents.has(specifier.imported.name)
        ) {
          localToComponent.set(
            String(specifier.local?.name ?? specifier.imported.name),
            String(specifier.imported.name),
          );
        } else if (
          specifier.type === "ImportNamespaceSpecifier" &&
          specifier.local
        ) {
          flowNamespaces.add(String(specifier.local.name));
        }
      }
    });

  if (localToComponent.size === 0 && flowNamespaces.size === 0) {
    return fileInfo.source;
  }

  root.find(j.JSXOpeningElement).forEach((path) => {
    const name = path.node.name;

    let isAffected = false;
    if (name.type === "JSXIdentifier") {
      isAffected = localToComponent.has(name.name);
    } else if (
      name.type === "JSXMemberExpression" &&
      name.object.type === "JSXIdentifier" &&
      name.property.type === "JSXIdentifier"
    ) {
      isAffected =
        flowNamespaces.has(name.object.name) &&
        affectedComponents.has(name.property.name);
    }

    if (!isAffected) {
      return;
    }

    for (const attribute of path.node.attributes ?? []) {
      if (
        attribute.type !== "JSXAttribute" ||
        attribute.name.type !== "JSXIdentifier" ||
        attribute.name.name !== "color"
      ) {
        continue;
      }

      const value = attribute.value;

      // color="primary"
      if (isPrimaryLiteral(value)) {
        attribute.value = j.stringLiteral("default");
        continue;
      }

      // color={"primary"}
      if (
        value?.type === "JSXExpressionContainer" &&
        isPrimaryLiteral(value.expression)
      ) {
        value.expression = j.stringLiteral("default");
      }
    }
  });

  return root.toSource();
};

const flowAlphaColorPrimaryToDefault = flowAlphaColorPrimaryToDefaultTransform;

/**
 * Runs every codemod on the way to `1.0.0` in one pass, in the order the
 * changes were released. Use it to catch up from an older `0.2.0-alpha` in one
 * go instead of running the transforms one by one.
 *
 * It is not the whole migration. Most entries in the migration guide have no
 * codemod and need a hand — this covers the renames a script can do.
 *
 * Two transforms in `src/transforms` are deliberately **not** part of it:
 *
 * - `flowRemote` converts an app to `@mittwald/flow-remote-react-components`.
 *   That is a port to a different package, not a migration, and running it on a
 *   normal app would rewrite every Flow import.
 * - `flow020` migrates `0.1.0` to `0.2.0` by collapsing subpath imports onto the
 *   package root. Since then the package gained subpath entries it does not
 *   know about (`/internal`, `/flr-universal`, `/mittwald-password-tools-js`),
 *   so on a current codebase it would break those imports. Run it separately,
 *   and only when coming from `0.1.0`.
 */
const flow1Transform: Transform = (fileInfo, api, options) => {
  /** Ordered by the release the respective change shipped in. */
  const transforms: Transform[] = [
    flowAlphaButtonPropsInterfaces, // alpha.646
    flowAlphaActionPropToOnAction, // alpha.646
    flowAlphaMutedActionErrorToAbortActionError, // alpha.712
    flowAlphaAccentBoxColorToBackgroundColor, // alpha.786
    flowAlphaPasswordToolsRule, // alpha.802
    flowAlphaColorPrimaryToDefault, // alpha.846
    flowAlphaButtonColorAccentToSuccess, // alpha.1046
    flowAlphaAlignToCombine, // alpha.1047
  ];

  let source = fileInfo.source;

  for (const transform of transforms) {
    // A transform returns the unchanged source, or nothing at all, when it does
    // not apply — both mean "keep what we have" and must not end the chain.
    const result = transform({ ...fileInfo, source }, api, options);
    if (typeof result === "string") {
      source = result;
    }
  }

  return source;
};

export default flow1Transform;
