declare const classNames: {
  readonly donutChart: "donutChart";
  readonly border: "border";
  readonly background: "background";
  readonly fill: "fill";
  readonly segment: "segment";
  readonly value: "value";
  readonly "size-l": "size-l";
  readonly info: "info";
  readonly success: "success";
  readonly danger: "danger";
  readonly warning: "warning";
  readonly donutChartContainer: "donutChartContainer";
  readonly bottom: "bottom";
  readonly top: "top";
  readonly right: "right";
  readonly legend: "legend";
  readonly left: "left";
};
export default classNames;
