declare const classNames: {
  readonly home: "home";
  readonly eyebrow: "eyebrow";
  readonly hero: "hero";
  readonly releaseTeaser: "releaseTeaser";
  readonly entryTile: "entryTile";
  readonly facts: "facts";
  readonly portal: "portal";
  readonly extensionsTeaser: "extensionsTeaser";
  readonly onDarkText: "onDarkText";
  readonly heroTitle: "heroTitle";
  readonly heroLead: "heroLead";
  readonly sectionTitle: "sectionTitle";
  readonly sectionLead: "sectionLead";
  readonly tileTitle: "tileTitle";
  readonly factTitle: "factTitle";
  readonly teasers: "teasers";
  readonly teaserContent: "teaserContent";
  readonly teaserPhoto: "teaserPhoto";
  readonly dx: "dx";
  readonly dxHead: "dxHead";
  readonly exampleCard: "exampleCard";
  readonly portalContent: "portalContent";
};
export default classNames;
