enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0086
    level: error
  - code: YN0068
    level: error
  - code: YN0069
    level: error

nodeLinker: pnp

packageExtensions:
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      vite: "*"
  "@nrwl/devkit@*":
    dependencies:
      nx: <9999
  "@nx/cypress@*":
    dependencies:
      eslint: "*"
      nx: <9999
      typescript: "*"
  "@nx/eslint@*":
    dependencies:
      nx: <9999
  "@nx/js@*":
    dependencies:
      "@types/node": "*"
      nx: <9999
      typescript: "*"
  "@nx/linter@*":
    dependencies:
      eslint: "*"
  "@nx/storybook@*":
    dependencies:
      eslint: "*"
      nx: <9999
      typescript: "*"
  "@storybook/addon-controls@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/builder-vite@*":
    dependencies:
      vite: "*"
  "@storybook/manager-api@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react-dom: "*"
  "@storybook/react-vite@*":
    dependencies:
      typescript: "*"
  "@typescript-eslint/type-utils@*":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"
  "@vitejs/plugin-react@*":
    dependencies:
      vite: "*"
  lerna@*:
    dependencies:
      strip-ansi: ^4
  typescript-eslint@*:
    dependencies:
      eslint: "*"

yarnPath: .yarn/releases/yarn-4.4.0.cjs
