enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0086
    level: warning
  - code: YN0068
    level: error
  - code: YN0069
    level: error

nodeLinker: node-modules

packageExtensions:
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      vite: "*"
  "@nx/cypress@*":
    dependencies:
      eslint: "*"
      nx: <9999
      typescript: "*"
  "@nx/eslint@*":
    dependencies:
      nx: <9999
  "@nx/js@*":
    dependencies:
      "@types/node": "*"
      nx: <9999
      typescript: "*"
  "@nx/storybook@*":
    dependencies:
      eslint: "*"
      nx: <9999
      typescript: "*"
  "@storybook/addon-controls@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": "*"
  "@storybook/builder-vite@*":
    dependencies:
      vite: "*"
  "@storybook/manager-api@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react-dom: "*"
  "@storybook/react-vite@*":
    dependencies:
      typescript: "*"
  "@storybook/test@*":
    dependencies:
      storybook: "*"
  "@testing-library/jest-dom@*":
    dependencies:
      vitest: "*"
  "@typescript-eslint/type-utils@*":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"
  "@vitejs/plugin-react@*":
    dependencies:
      vite: "*"
  acorn-jsx@*:
    dependencies:
      acorn: "*"
  typescript-eslint@*:
    dependencies:
      eslint: "*"

yarnPath: .yarn/releases/yarn-4.5.3.cjs
