nodeLinker: pnp
enableScripts: false
enableGlobalCache: false

yarnPath: .yarn/releases/yarn-4.0.1.cjs

packageExtensions:
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      "react-dom": "*"
  "@storybook/builder-vite@*":
    dependencies:
      vite: "*"
  "@vitejs/plugin-react@*":
    dependencies:
      vite: "*"
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      vite: "*"
  "eslint-config-next@*":
    dependencies:
      next: "*"
