enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0086
    level: error

nodeLinker: pnp

packageExtensions:
  "@joshwooding/vite-plugin-react-docgen-typescript@*":
    dependencies:
      vite: "*"
  "@storybook/builder-vite@*":
    dependencies:
      vite: "*"
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-vite": "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react-dom: "*"
  "@vitejs/plugin-react@*":
    dependencies:
      vite: "*"
  eslint-config-next@*:
    dependencies:
      next: "*"

yarnPath: .yarn/releases/yarn-4.2.1.cjs
