patchedDependencies:
  "@quilted/threads@3.3.1": "patches/@quilted__threads@3.3.1.patch"
  "acorn": "patches/acorn.patch"

packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 10080 # 1 week in minutes
minimumReleaseAgeExclude:
  - "@mittwald/*"