server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;
    charset_types text/plain text/css text/xml application/javascript application/json;

    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 404 /404.html;
}

