export type User = (typeof users)[number];

const apiSleep = (): Promise<void> =>
  new Promise((res) => window.setTimeout(res, 500));

export const getStates = async () => {
  await apiSleep();
  return states;
};

interface Request {
  pagination?: {
    limit: number;
    skip: number;
  };
  filter?: {
    states?: string[];
  };
}

interface Response {
  data: User[];
  totalCount: number;
}

export const getUsers = async (req: Request): Promise<Response> => {
  await apiSleep();

  const states = req.filter?.states;

  const preFilteredData =
    states === undefined
      ? users
      : users.filter(
          (u) => states.length === 0 || states.includes(u.location.state),
        );
  const totalCount = preFilteredData.length;

  return {
    data: req.pagination
      ? preFilteredData.slice(
          req.pagination.skip,
          req.pagination.skip + req.pagination.limit,
        )
      : preFilteredData,
    totalCount,
  };
};

export const users = [
  {
    status: "disabled",
    name: {
      first: "Felipa",
      middle: "Bailey",
      last: "Wolf",
    },
    username: "Felipa-Wolf",
    password: "BJM0CzeIAeuNKG6",
    emails: ["Edwina.Adams@example.com", "Gabrielle.Lemke21@gmail.com"],
    phoneNumber: "(892) 369-5820 x78530",
    location: {
      street: "58818 Zemlak Roads",
      city: "West Dora",
      state: "Florida",
      country: "Kiribati",
      zip: "13790-9909",
      coordinates: {
        latitude: -42.7219,
        longitude: -156.2339,
      },
    },
    website: "https://colorful-screwdriver.biz",
    domain: "agonizing-beef.info",
    job: {
      title: "Senior Communications Analyst",
      descriptor: "Corporate",
      area: "Operations",
      type: "Executive",
      company: "Bartoletti, Crona and Balistreri",
    },
    creditCard: {
      number: "4593743878944",
      cvv: "199",
      issuer: "diners_club",
    },
    uuid: "294eadda-2a09-48f8-90ad-33480a3dc0cd",
    objectId: "65f825e6147562cde0f14043",
  },
  {
    status: "active",
    name: {
      first: "Dariana",
      middle: "Sawyer",
      last: "Emard",
    },
    username: "Dariana-Emard",
    password: "bL5Z8oCio6XWb4Q",
    emails: ["Kennith.Kuphal85@gmail.com", "Kaylee86@example.com"],
    phoneNumber: "409.923.9806 x18534",
    location: {
      street: "7637 Laura Walks",
      city: "South Leathaville",
      state: "California",
      country: "Egypt",
      zip: "71617-0206",
      coordinates: {
        latitude: 35.1969,
        longitude: -91.0115,
      },
    },
    website: "https://supportive-monitoring.name",
    domain: "excited-textbook.net",
    job: {
      title: "Investor Solutions Manager",
      descriptor: "Legacy",
      area: "Infrastructure",
      type: "Producer",
      company: "Haag and Sons",
    },
    creditCard: {
      number: "4991-2319-2154-2464",
      cvv: "668",
      issuer: "jcb",
    },
    uuid: "cc917bd8-62c4-42e9-87ac-27e10dfbb0fe",
    objectId: "65f825e6147562cde0f14044",
  },
  {
    status: "active",
    name: {
      first: "Alivia",
      middle: "Rowan",
      last: "Balistreri",
    },
    username: "Alivia-Balistreri",
    password: "3ySLn_ZcLmwHNYp",
    emails: ["Bo.Murphy93@example.com", "Emery_Cole@gmail.com"],
    phoneNumber: "(345) 885-4626",
    location: {
      street: "432 McKenzie Divide",
      city: "Kassulkeville",
      state: "New Hampshire",
      country: "Latvia",
      zip: "02648",
      coordinates: {
        latitude: -16.9368,
        longitude: -6.8776,
      },
    },
    website: "https://giant-reversal.name",
    domain: "emotional-patrol.biz",
    job: {
      title: "Lead Metrics Orchestrator",
      descriptor: "Dynamic",
      area: "Markets",
      type: "Representative",
      company: "Collier Inc",
    },
    creditCard: {
      number: "4594989585201",
      cvv: "776",
      issuer: "diners_club",
    },
    uuid: "c19a4ff5-9566-4cc3-aaf4-686d19855414",
    objectId: "65f825e6147562cde0f14045",
  },
  {
    status: "disabled",
    name: {
      first: "Khalil",
      middle: "Reese",
      last: "Windler",
    },
    username: "Khalil-Windler",
    password: "LGDLtwTWsRs9mQH",
    emails: ["Uriah.Miller81@gmail.com", "Gianni_Thompson75@example.com"],
    phoneNumber: "1-956-698-1332 x53122",
    location: {
      street: "546 Geovany Greens",
      city: "Lowell",
      state: "South Carolina",
      country: "Qatar",
      zip: "77951",
      coordinates: {
        latitude: 20.7881,
        longitude: -170.8789,
      },
    },
    website: "https://solid-shear.biz/",
    domain: "satisfied-arcade.info",
    job: {
      title: "Future Identity Representative",
      descriptor: "Direct",
      area: "Quality",
      type: "Specialist",
      company: "Turner - Ritchie",
    },
    creditCard: {
      number: "6011-6291-3887-2765-0044",
      cvv: "638",
      issuer: "jcb",
    },
    uuid: "8c0bb0cf-cbfe-4b37-be1a-47daa9d2967c",
    objectId: "65f825e6147562cde0f14046",
  },
  {
    status: "disabled",
    name: {
      first: "Fannie",
      middle: "Phoenix",
      last: "Sawayn",
    },
    username: "Fannie-Sawayn",
    password: "losBk8Zw8SuNlN9",
    emails: ["Keaton.Abernathy60@gmail.com", "Kathryne87@gmail.com"],
    phoneNumber: "1-375-294-3726 x7490",
    location: {
      street: "8481 Kub Forges",
      city: "Reynoldsstead",
      state: "Maine",
      country: "South Georgia and the South Sandwich Islands",
      zip: "99212",
      coordinates: {
        latitude: 0.3053,
        longitude: -86.0834,
      },
    },
    website: "https://medical-credenza.net/",
    domain: "powerless-timbale.com",
    job: {
      title: "International Directives Orchestrator",
      descriptor: "Forward",
      area: "Data",
      type: "Orchestrator",
      company: "Larson - Weimann",
    },
    creditCard: {
      number: "6477-0914-6877-3528",
      cvv: "414",
      issuer: "visa",
    },
    uuid: "3dfdfc07-7840-4143-9a3c-9209453dae4c",
    objectId: "65f825e6147562cde0f14047",
  },
  {
    status: "active",
    name: {
      first: "Mac",
      middle: "Anderson",
      last: "Reynolds",
    },
    username: "Mac-Reynolds",
    password: "TnpvjwEOgZiBbHG",
    emails: ["Ned_Keeling35@gmail.com", "Reese.Williamson@example.com"],
    phoneNumber: "(774) 920-7190 x0242",
    location: {
      street: "85781 Randal Rue",
      city: "North Hadleyside",
      state: "New Mexico",
      country: "Ecuador",
      zip: "02376-3883",
      coordinates: {
        latitude: 20.1446,
        longitude: -9.1214,
      },
    },
    website: "https://soulful-enrollment.org/",
    domain: "elliptical-skiing.info",
    job: {
      title: "Global Branding Producer",
      descriptor: "Investor",
      area: "Creative",
      type: "Specialist",
      company: "Herman - Witting",
    },
    creditCard: {
      number: "6771-8906-0531-7112",
      cvv: "144",
      issuer: "american_express",
    },
    uuid: "153c5836-1c2c-4a42-bcf5-a0f284c7ac26",
    objectId: "65f825e6147562cde0f14048",
  },
  {
    status: "disabled",
    name: {
      first: "Elizabeth",
      middle: "Leslie",
      last: "Quigley",
    },
    username: "Elizabeth-Quigley",
    password: "qR5zgO2pWIDDFQ2",
    emails: ["Samantha_McLaughlin@example.com", "Delia.Beier48@example.com"],
    phoneNumber: "1-455-696-9451 x2816",
    location: {
      street: "72248 Chadrick Ferry",
      city: "Elysestead",
      state: "Illinois",
      country: "Macao",
      zip: "51617",
      coordinates: {
        latitude: 17.9795,
        longitude: -96.1731,
      },
    },
    website: "https://frayed-fortune.net/",
    domain: "popular-dhow.net",
    job: {
      title: "Customer Optimization Officer",
      descriptor: "Customer",
      area: "Interactions",
      type: "Representative",
      company: "Homenick, Von and Effertz",
    },
    creditCard: {
      number: "3529-2559-0615-9161",
      cvv: "699",
      issuer: "jcb",
    },
    uuid: "52bb0291-e80d-497c-8dd5-7d3455aaac92",
    objectId: "65f825e6147562cde0f14049",
  },
  {
    status: "active",
    name: {
      first: "Jeremie",
      middle: "Leslie",
      last: "Hickle",
    },
    username: "Jeremie-Hickle",
    password: "UjMyjo3Ri252lNv",
    emails: ["Georgette.Rempel@gmail.com", "Valerie.Gibson47@example.com"],
    phoneNumber: "973.708.1649",
    location: {
      street: "157 Bethany Cliff",
      city: "Santee",
      state: "California",
      country: "Nigeria",
      zip: "01590",
      coordinates: {
        latitude: -65.6912,
        longitude: 70.5328,
      },
    },
    website: "https://vigilant-cleft.info",
    domain: "authentic-perfection.org",
    job: {
      title: "Corporate Paradigm Representative",
      descriptor: "District",
      area: "Applications",
      type: "Orchestrator",
      company: "Hermann - Smitham",
    },
    creditCard: {
      number: "4468002304843",
      cvv: "022",
      issuer: "visa",
    },
    uuid: "ab0da28f-8e50-4f94-83ed-792993248d4b",
    objectId: "65f825e6147562cde0f1404a",
  },
  {
    status: "active",
    name: {
      first: "Ladarius",
      middle: "Blake",
      last: "Witting",
    },
    username: "Ladarius-Witting",
    password: "bNbneeZxTgEWWLl",
    emails: ["Deonte_Paucek@example.com", "Bradford.Runolfsson17@example.com"],
    phoneNumber: "953-525-9450 x0623",
    location: {
      street: "6554 Madyson Valley",
      city: "North Mylene",
      state: "Indiana",
      country: "Bouvet Island",
      zip: "83472",
      coordinates: {
        latitude: 33.0343,
        longitude: 74.767,
      },
    },
    website: "https://hearty-collection.name",
    domain: "first-position.com",
    job: {
      title: "Corporate Factors Manager",
      descriptor: "Global",
      area: "Program",
      type: "Consultant",
      company: "Leffler - Ferry",
    },
    creditCard: {
      number: "3726-888774-06043",
      cvv: "426",
      issuer: "american_express",
    },
    uuid: "86a64d87-36ab-4064-b138-b6981589eac1",
    objectId: "65f825e6147562cde0f1404b",
  },
  {
    status: "active",
    name: {
      first: "Mortimer",
      middle: "Kendall",
      last: "Jones",
    },
    username: "Mortimer-Jones",
    password: "_jXXVMqSjx30veu",
    emails: ["Jordane_Ledner81@gmail.com", "Evert.Mraz@example.com"],
    phoneNumber: "(876) 470-2989 x035",
    location: {
      street: "193 Marquardt Valleys",
      city: "Lansing",
      state: "North Carolina",
      country: "Pitcairn Islands",
      zip: "18903",
      coordinates: {
        latitude: -28.3852,
        longitude: -170.1651,
      },
    },
    website: "https://worst-classification.com",
    domain: "amused-cage.org",
    job: {
      title: "Direct Infrastructure Director",
      descriptor: "Forward",
      area: "Mobility",
      type: "Representative",
      company: "Kautzer, Bode and O'Connell",
    },
    creditCard: {
      number: "4535-6033-3546-4944",
      cvv: "990",
      issuer: "maestro",
    },
    uuid: "184729c3-6381-4fdf-a6de-f5545f90e0bd",
    objectId: "65f825e6147562cde0f1404c",
  },
  {
    status: "active",
    name: {
      first: "Adella",
      middle: "Taylor",
      last: "Gutkowski-Lemke",
    },
    username: "Adella-Gutkowski-Lemke",
    password: "F9bougzyZmeubKw",
    emails: ["Chelsie.Haley-OReilly47@gmail.com", "Tracy13@example.com"],
    phoneNumber: "565.987.7292 x76418",
    location: {
      street: "46340 Santa Oval",
      city: "Honolulu",
      state: "Mississippi",
      country: "Kenya",
      zip: "73305-1120",
      coordinates: {
        latitude: -33.7386,
        longitude: -133.0771,
      },
    },
    website: "https://puny-beanstalk.name/",
    domain: "subtle-octet.net",
    job: {
      title: "District Infrastructure Representative",
      descriptor: "Global",
      area: "Creative",
      type: "Representative",
      company: "Hartmann LLC",
    },
    creditCard: {
      number: "3048-082168-0186",
      cvv: "276",
      issuer: "diners_club",
    },
    uuid: "88a96c4a-54b6-4cab-92fc-0c72d2ba1c99",
    objectId: "65f825e6147562cde0f1404d",
  },
  {
    status: "disabled",
    name: {
      first: "Lindsay",
      middle: "Marlowe",
      last: "Stroman",
    },
    username: "Lindsay-Stroman",
    password: "jbl468i_tsYsCOE",
    emails: ["Peggie_Baumbach62@example.com", "Marcelino22@example.com"],
    phoneNumber: "329.491.6492",
    location: {
      street: "95981 Friesen Cliffs",
      city: "Loveland",
      state: "Arizona",
      country: "United States of America",
      zip: "66450",
      coordinates: {
        latitude: -83.5621,
        longitude: -20.8014,
      },
    },
    website: "https://virtuous-lark.info/",
    domain: "medical-textual.org",
    job: {
      title: "Direct Assurance Coordinator",
      descriptor: "Human",
      area: "Usability",
      type: "Coordinator",
      company: "Jacobs, Dare and Mosciski",
    },
    creditCard: {
      number: "5038-2739-7309-4509",
      cvv: "801",
      issuer: "mastercard",
    },
    uuid: "8cee8db9-5710-4adf-af9e-1933e2e439b0",
    objectId: "65f825e6147562cde0f1404e",
  },
  {
    status: "active",
    name: {
      first: "Donny",
      middle: "London",
      last: "McKenzie",
    },
    username: "Donny-McKenzie",
    password: "f_rag7bQitWkPEy",
    emails: ["Brain.Lockman@example.com", "Camryn_Heaney@example.com"],
    phoneNumber: "(877) 603-4264",
    location: {
      street: "39621 Robb Track",
      city: "Flatleystead",
      state: "Idaho",
      country: "Tunisia",
      zip: "65719-4338",
      coordinates: {
        latitude: 27.519,
        longitude: -177.3368,
      },
    },
    website: "https://lighthearted-physics.biz/",
    domain: "whispered-teaching.name",
    job: {
      title: "Senior Integration Consultant",
      descriptor: "Future",
      area: "Configuration",
      type: "Strategist",
      company: "Bayer and Sons",
    },
    creditCard: {
      number: "5478-3569-3130-5401",
      cvv: "752",
      issuer: "discover",
    },
    uuid: "5981cf44-c59a-4752-85be-4328d5e10305",
    objectId: "65f825e6147562cde0f1404f",
  },
  {
    status: "disabled",
    name: {
      first: "Paolo",
      middle: "Gray",
      last: "Watsica",
    },
    username: "Paolo-Watsica",
    password: "eNSLPwrsbBmgV8r",
    emails: ["Rubie_Russel@gmail.com", "Arturo.Dickinson33@gmail.com"],
    phoneNumber: "(740) 746-5816 x145",
    location: {
      street: "1653 Walker Hollow",
      city: "Lake Guido",
      state: "Utah",
      country: "Mauritania",
      zip: "62967",
      coordinates: {
        latitude: -54.014,
        longitude: -6.4278,
      },
    },
    website: "https://growling-regret.org/",
    domain: "decisive-binoculars.info",
    job: {
      title: "Dynamic Security Director",
      descriptor: "Human",
      area: "Data",
      type: "Representative",
      company: "Harris Inc",
    },
    creditCard: {
      number: "6771-8930-1329-1630",
      cvv: "851",
      issuer: "mastercard",
    },
    uuid: "6e8bcdf4-cea1-415f-832d-4fa025ee3c1f",
    objectId: "65f825e6147562cde0f14050",
  },
  {
    status: "active",
    name: {
      first: "Rocio",
      middle: "Nico",
      last: "Kerluke",
    },
    username: "Rocio-Kerluke",
    password: "es_kYEKM1Qk_AAv",
    emails: [
      "Edgar.Oberbrunner44@example.com",
      "Keely_Christiansen6@gmail.com",
    ],
    phoneNumber: "(548) 996-9757 x08939",
    location: {
      street: "2929 Kuphal Drives",
      city: "Haneton",
      state: "Georgia",
      country: "Bulgaria",
      zip: "83909",
      coordinates: {
        latitude: 44.4575,
        longitude: -53.6785,
      },
    },
    website: "https://fumbling-tarragon.biz/",
    domain: "ringed-savannah.com",
    job: {
      title: "Regional Applications Supervisor",
      descriptor: "Direct",
      area: "Tactics",
      type: "Orchestrator",
      company: "Luettgen - Prohaska",
    },
    creditCard: {
      number: "3732-866616-55070",
      cvv: "958",
      issuer: "american_express",
    },
    uuid: "c8d57e19-7ef2-4f87-b447-df42b3b447e2",
    objectId: "65f825e6147562cde0f14051",
  },
  {
    status: "disabled",
    name: {
      first: "Roselyn",
      middle: "Jules",
      last: "DuBuque",
    },
    username: "Roselyn-DuBuque",
    password: "Chit0mhaXy9p41I",
    emails: ["Eddie.Hermiston36@gmail.com", "Orin75@example.com"],
    phoneNumber: "922.543.2334 x24293",
    location: {
      street: "3279 Lang Way",
      city: "West Emilio",
      state: "Vermont",
      country: "Uruguay",
      zip: "95238-4449",
      coordinates: {
        latitude: 2.33,
        longitude: 46.7609,
      },
    },
    website: "https://zesty-sauerkraut.com",
    domain: "sleepy-chalice.info",
    job: {
      title: "Legacy Solutions Representative",
      descriptor: "Global",
      area: "Usability",
      type: "Designer",
      company: "Kling, Dibbert and Beer",
    },
    creditCard: {
      number: "6759-4746-5023-0516",
      cvv: "609",
      issuer: "diners_club",
    },
    uuid: "e2d5199b-48cd-47ad-9e95-177c2c0b5647",
    objectId: "65f825e6147562cde0f14052",
  },
  {
    status: "disabled",
    name: {
      first: "Jayde",
      middle: "Ryan",
      last: "Hickle",
    },
    username: "Jayde-Hickle",
    password: "B91w7pwAs6UOR6T",
    emails: ["Verda_Farrell50@gmail.com", "Imani26@example.com"],
    phoneNumber: "(863) 835-4447 x602",
    location: {
      street: "7083 Brakus Crossing",
      city: "Margate",
      state: "New Mexico",
      country: "Gambia",
      zip: "78274",
      coordinates: {
        latitude: 87.5115,
        longitude: -165.7833,
      },
    },
    website: "https://those-gallon.org/",
    domain: "aggressive-chafe.com",
    job: {
      title: "Investor Configuration Technician",
      descriptor: "Human",
      area: "Marketing",
      type: "Orchestrator",
      company: "Medhurst, McCullough and Jerde",
    },
    creditCard: {
      number: "675993030111538562",
      cvv: "459",
      issuer: "mastercard",
    },
    uuid: "4ac78d52-f31d-488f-b85c-f1333b04651e",
    objectId: "65f825e6147562cde0f14053",
  },
  {
    status: "disabled",
    name: {
      first: "Sofia",
      middle: "Leslie",
      last: "Kuhic",
    },
    username: "Sofia-Kuhic",
    password: "h_LUQBegjHf80Aa",
    emails: ["Itzel65@gmail.com", "Emma_Goldner37@example.com"],
    phoneNumber: "748-482-2370 x7104",
    location: {
      street: "6481 Felton Plains",
      city: "Roseville",
      state: "North Carolina",
      country: "Antigua and Barbuda",
      zip: "74316-5889",
      coordinates: {
        latitude: 69.2278,
        longitude: 44.7129,
      },
    },
    website: "https://scholarly-continuity.com/",
    domain: "high-level-crewman.net",
    job: {
      title: "Direct Configuration Strategist",
      descriptor: "Legacy",
      area: "Web",
      type: "Specialist",
      company: "Erdman - Kautzer",
    },
    creditCard: {
      number: "3040-706046-0103",
      cvv: "033",
      issuer: "visa",
    },
    uuid: "880a1000-8f1c-45d6-ac52-9662aaa63763",
    objectId: "65f825e6147562cde0f14054",
  },
  {
    status: "active",
    name: {
      first: "Moises",
      middle: "Jamie",
      last: "Kertzmann",
    },
    username: "Moises-Kertzmann",
    password: "RZvYSw_vUyoirxz",
    emails: ["Fermin.Muller50@gmail.com", "Keeley_Schroeder@example.com"],
    phoneNumber: "(362) 877-9184 x1944",
    location: {
      street: "791 Aiden Dale",
      city: "New Noelview",
      state: "Rhode Island",
      country: "Poland",
      zip: "84897",
      coordinates: {
        latitude: 58.7237,
        longitude: -4.0724,
      },
    },
    website: "https://lost-display.com/",
    domain: "muffled-nitrogen.net",
    job: {
      title: "Legacy Functionality Agent",
      descriptor: "Senior",
      area: "Web",
      type: "Orchestrator",
      company: "Langworth, Maggio and Hansen",
    },
    creditCard: {
      number: "3027-024488-9179",
      cvv: "093",
      issuer: "maestro",
    },
    uuid: "ac590fd7-4433-4e12-96ed-8870aa142f66",
    objectId: "65f825e6147562cde0f14055",
  },
  {
    status: "disabled",
    name: {
      first: "Betty",
      middle: "Taylor",
      last: "Jacobson-Stiedemann",
    },
    username: "Betty-Jacobson-Stiedemann",
    password: "2vCzCtX1QePfQd9",
    emails: ["Mitchel.Miller@example.com", "Gloria.Streich@gmail.com"],
    phoneNumber: "924.302.5377 x826",
    location: {
      street: "147 Celia Crest",
      city: "Fort Demetris",
      state: "Alaska",
      country: "Sint Maarten",
      zip: "80486-3418",
      coordinates: {
        latitude: 81.7285,
        longitude: -104.7897,
      },
    },
    website: "https://handmade-attempt.biz",
    domain: "kaleidoscopic-font.name",
    job: {
      title: "Future Communications Assistant",
      descriptor: "Regional",
      area: "Markets",
      type: "Coordinator",
      company: "Jacobi, Bogan and Frami",
    },
    creditCard: {
      number: "6771-8990-3696-8823",
      cvv: "707",
      issuer: "maestro",
    },
    uuid: "c1e2a34a-23e5-4c8b-bee8-93cddd85a0e9",
    objectId: "65f825e6147562cde0f14056",
  },
  {
    status: "disabled",
    name: {
      first: "Lonnie",
      middle: "Brooklyn",
      last: "O'Kon",
    },
    username: "Lonnie-O'Kon",
    password: "JK1VIL6lIdi7JVB",
    emails: ["Amos.Langworth36@example.com", "Carlie_Runolfsson@example.com"],
    phoneNumber: "489.876.0026 x37393",
    location: {
      street: "60236 Smitham Green",
      city: "Schmelerchester",
      state: "Ohio",
      country: "Virgin Islands, U.S.",
      zip: "68301",
      coordinates: {
        latitude: 79.0179,
        longitude: -95.6385,
      },
    },
    website: "https://shady-giraffe.org/",
    domain: "striped-decency.net",
    job: {
      title: "Investor Group Specialist",
      descriptor: "Lead",
      area: "Operations",
      type: "Architect",
      company: "Torp Group",
    },
    creditCard: {
      number: "67596532919477852",
      cvv: "207",
      issuer: "jcb",
    },
    uuid: "d436b251-6c5a-4ea4-ae99-1dc1664b3471",
    objectId: "65f825e6147562cde0f14057",
  },
  {
    status: "disabled",
    name: {
      first: "Verona",
      middle: "Alex",
      last: "Bailey",
    },
    username: "Verona-Bailey",
    password: "EUiPAZKHAoKFfiS",
    emails: ["Vaughn1@example.com", "Neil.Ullrich@example.com"],
    phoneNumber: "629-779-6876 x3686",
    location: {
      street: "808 Macejkovic Grove",
      city: "Johnboro",
      state: "Delaware",
      country: "El Salvador",
      zip: "23248-8594",
      coordinates: {
        latitude: 87.4167,
        longitude: -47.256,
      },
    },
    website: "https://emotional-blackbird.biz",
    domain: "burly-beginning.biz",
    job: {
      title: "Corporate Implementation Producer",
      descriptor: "Internal",
      area: "Factors",
      type: "Technician",
      company: "Jacobs Inc",
    },
    creditCard: {
      number: "3051-813042-2020",
      cvv: "708",
      issuer: "american_express",
    },
    uuid: "5e971ad3-0682-441d-9352-cb6325130414",
    objectId: "65f825e6147562cde0f14058",
  },
  {
    status: "active",
    name: {
      first: "Ezekiel",
      middle: "Blake",
      last: "Hamill",
    },
    username: "Ezekiel-Hamill",
    password: "8mkw1ucfMcfotUz",
    emails: ["Catalina.Kuvalis@example.com", "Quincy39@example.com"],
    phoneNumber: "755-396-2380 x93415",
    location: {
      street: "3436 Landen Land",
      city: "Lucioside",
      state: "Hawaii",
      country: "Chile",
      zip: "47125-4381",
      coordinates: {
        latitude: -7.6709,
        longitude: -156.6168,
      },
    },
    website: "https://bruised-boulevard.net",
    domain: "jumbo-wolf.net",
    job: {
      title: "Senior Metrics Specialist",
      descriptor: "Chief",
      area: "Usability",
      type: "Engineer",
      company: "Williamson Group",
    },
    creditCard: {
      number: "4096773517804",
      cvv: "486",
      issuer: "visa",
    },
    uuid: "a8d68d2a-10cf-469a-8ee7-07919e1bfaa7",
    objectId: "65f825e6147562cde0f14059",
  },
  {
    status: "disabled",
    name: {
      first: "Tyrese",
      middle: "Ryan",
      last: "Batz",
    },
    username: "Tyrese-Batz",
    password: "E8v8bkA5YzC8eb_",
    emails: ["Glennie.Bartell41@gmail.com", "Kristin.Auer@example.com"],
    phoneNumber: "901.593.9429",
    location: {
      street: "49522 Conrad Land",
      city: "Herzogberg",
      state: "West Virginia",
      country: "American Samoa",
      zip: "04234",
      coordinates: {
        latitude: 12.9572,
        longitude: -160.5988,
      },
    },
    website: "https://keen-flow.biz/",
    domain: "considerate-optimist.net",
    job: {
      title: "Principal Communications Officer",
      descriptor: "Future",
      area: "Markets",
      type: "Specialist",
      company: "Sanford LLC",
    },
    creditCard: {
      number: "6304-4050-5543-9559",
      cvv: "418",
      issuer: "discover",
    },
    uuid: "985869f1-913d-4eff-ac1f-33db52551b81",
    objectId: "65f825e6147562cde0f1405a",
  },
  {
    status: "disabled",
    name: {
      first: "Fanny",
      middle: "Bowie",
      last: "Wuckert",
    },
    username: "Fanny-Wuckert",
    password: "63UZdtfNgu6b0gG",
    emails: ["Jane57@gmail.com", "Rebeka53@gmail.com"],
    phoneNumber: "308.288.2801 x850",
    location: {
      street: "99501 Pfeffer Dam",
      city: "North Charleston",
      state: "Kansas",
      country: "Oman",
      zip: "84536-9740",
      coordinates: {
        latitude: 73.902,
        longitude: 109.0051,
      },
    },
    website: "https://regal-jaguar.biz",
    domain: "voluminous-ottoman.org",
    job: {
      title: "Legacy Implementation Director",
      descriptor: "Chief",
      area: "Applications",
      type: "Technician",
      company: "Lockman Group",
    },
    creditCard: {
      number: "6759210714627275",
      cvv: "278",
      issuer: "jcb",
    },
    uuid: "87982875-bfe8-43cd-a627-ffc0b379acb7",
    objectId: "65f825e6147562cde0f1405b",
  },
  {
    status: "active",
    name: {
      first: "Arch",
      middle: "Kyle",
      last: "Veum",
    },
    username: "Arch-Veum",
    password: "eUb5No9IlcNn2ZL",
    emails: ["Ayden66@gmail.com", "Zena.Reichert8@example.com"],
    phoneNumber: "577-995-2132",
    location: {
      street: "1696 Jerrod Pines",
      city: "Cheyennefurt",
      state: "Maryland",
      country: "Kazakhstan",
      zip: "44282-7687",
      coordinates: {
        latitude: -88.4936,
        longitude: -81.8398,
      },
    },
    website: "https://frugal-monocle.com/",
    domain: "handsome-throne.name",
    job: {
      title: "Future Intranet Administrator",
      descriptor: "Human",
      area: "Response",
      type: "Producer",
      company: "Mills, Mraz and Sanford",
    },
    creditCard: {
      number: "3776-259353-94006",
      cvv: "282",
      issuer: "visa",
    },
    uuid: "8aa3be53-71e6-495c-acac-9faa128a322f",
    objectId: "65f825e6147562cde0f1405c",
  },
  {
    status: "disabled",
    name: {
      first: "Jayce",
      middle: "Robin",
      last: "Vandervort",
    },
    username: "Jayce-Vandervort",
    password: "RfS7gYqHFtWQvVb",
    emails: ["Friedrich.Bergstrom@example.com", "Verna18@gmail.com"],
    phoneNumber: "327-936-8135 x3201",
    location: {
      street: "28439 Elbert Rest",
      city: "Rolfsonshire",
      state: "Utah",
      country: "Falkland Islands (Malvinas)",
      zip: "69824-5472",
      coordinates: {
        latitude: 33.6725,
        longitude: -60.9122,
      },
    },
    website: "https://magnificent-couch.biz",
    domain: "wilted-bunkhouse.biz",
    job: {
      title: "National Assurance Executive",
      descriptor: "Legacy",
      area: "Branding",
      type: "Supervisor",
      company: "Bruen, Herman and Goyette",
    },
    creditCard: {
      number: "3747-461673-98011",
      cvv: "320",
      issuer: "jcb",
    },
    uuid: "1c8bccec-53de-4e8a-853f-b78bccdb4d2a",
    objectId: "65f825e6147562cde0f1405d",
  },
  {
    status: "active",
    name: {
      first: "Florida",
      middle: "Gray",
      last: "Macejkovic",
    },
    username: "Florida-Macejkovic",
    password: "eluxMYKtSIvPxr9",
    emails: ["Barton_Tremblay19@example.com", "Delpha68@gmail.com"],
    phoneNumber: "(268) 709-0206",
    location: {
      street: "4285 Steuber Run",
      city: "Daytona Beach",
      state: "Arkansas",
      country: "Venezuela",
      zip: "00638-5748",
      coordinates: {
        latitude: -50.5964,
        longitude: 16.0711,
      },
    },
    website: "https://blank-conception.info",
    domain: "royal-rap.net",
    job: {
      title: "Dynamic Communications Architect",
      descriptor: "Chief",
      area: "Usability",
      type: "Strategist",
      company: "Grimes Group",
    },
    creditCard: {
      number: "4706719696633",
      cvv: "627",
      issuer: "jcb",
    },
    uuid: "df1a6974-3068-4be5-8b8a-6a6efd999f0c",
    objectId: "65f825e6147562cde0f1405e",
  },
  {
    status: "disabled",
    name: {
      first: "Lea",
      middle: "Sawyer",
      last: "Romaguera",
    },
    username: "Lea-Romaguera",
    password: "RGaRjQS4LcxEHkj",
    emails: ["Aisha.Kertzmann@gmail.com", "Tiffany_Kunde63@example.com"],
    phoneNumber: "(979) 767-7448",
    location: {
      street: "7757 Nicolas Ways",
      city: "North Lorenz",
      state: "Kansas",
      country: "Anguilla",
      zip: "84090-0712",
      coordinates: {
        latitude: -86.2789,
        longitude: -69.788,
      },
    },
    website: "https://robust-gentleman.biz",
    domain: "lovely-angle.name",
    job: {
      title: "Human Usability Producer",
      descriptor: "Investor",
      area: "Mobility",
      type: "Associate",
      company: "Streich Group",
    },
    creditCard: {
      number: "6771-8948-6923-0912",
      cvv: "998",
      issuer: "american_express",
    },
    uuid: "0a2ff7e3-e234-42e4-82f1-83978f0f1e1c",
    objectId: "65f825e6147562cde0f1405f",
  },
  {
    status: "active",
    name: {
      first: "Yessenia",
      middle: "Jules",
      last: "Murray",
    },
    username: "Yessenia-Murray",
    password: "xwKdY0e8kSsO_Lp",
    emails: ["Ubaldo64@gmail.com", "Stanton_Ziemann@example.com"],
    phoneNumber: "(345) 279-7854",
    location: {
      street: "597 Karlee Dam",
      city: "North Claudia",
      state: "West Virginia",
      country: "Kuwait",
      zip: "02902",
      coordinates: {
        latitude: 82.576,
        longitude: -149.695,
      },
    },
    website: "https://unimportant-cupcake.name",
    domain: "warped-nougat.biz",
    job: {
      title: "Central Response Producer",
      descriptor: "International",
      area: "Implementation",
      type: "Associate",
      company: "Kuphal - Goyette",
    },
    creditCard: {
      number: "4064-8554-4143-3556",
      cvv: "511",
      issuer: "diners_club",
    },
    uuid: "72928f25-9940-4f66-89dd-3e453204913d",
    objectId: "65f825e6147562cde0f14060",
  },
  {
    status: "disabled",
    name: {
      first: "Sigmund",
      middle: "Shiloh",
      last: "Mertz",
    },
    username: "Sigmund-Mertz",
    password: "gUwVYuZDcZMAhPO",
    emails: ["Bobbie26@gmail.com", "Clement.Beahan19@example.com"],
    phoneNumber: "(767) 606-9991 x5898",
    location: {
      street: "2919 Krista Cliffs",
      city: "Sawaynside",
      state: "Colorado",
      country: "Burundi",
      zip: "38019-0251",
      coordinates: {
        latitude: -39.1232,
        longitude: -106.5146,
      },
    },
    website: "https://vigorous-deodorant.biz",
    domain: "untimely-childbirth.org",
    job: {
      title: "Senior Brand Analyst",
      descriptor: "Senior",
      area: "Operations",
      type: "Facilitator",
      company: "Reilly and Sons",
    },
    creditCard: {
      number: "4112024550815",
      cvv: "551",
      issuer: "maestro",
    },
    uuid: "5060866d-68f5-4022-ade0-275621eb7e89",
    objectId: "65f825e6147562cde0f14061",
  },
  {
    status: "disabled",
    name: {
      first: "Megane",
      middle: "London",
      last: "Aufderhar",
    },
    username: "Megane-Aufderhar",
    password: "EKeLkOpa1VxQhFU",
    emails: ["Arvid_Fritsch@gmail.com", "Eric_Corwin34@gmail.com"],
    phoneNumber: "821-617-0727 x6907",
    location: {
      street: "2190 Lucas Forest",
      city: "Auerstead",
      state: "Florida",
      country: "Turkmenistan",
      zip: "69607",
      coordinates: {
        latitude: 35.0087,
        longitude: 163.8701,
      },
    },
    website: "https://majestic-contribution.com",
    domain: "brilliant-eponym.biz",
    job: {
      title: "Regional Communications Planner",
      descriptor: "Senior",
      area: "Usability",
      type: "Associate",
      company: "Moore - Schmitt",
    },
    creditCard: {
      number: "4097-4162-3543-9308",
      cvv: "305",
      issuer: "maestro",
    },
    uuid: "503c7c06-da2d-4d34-94ac-e416055c3f81",
    objectId: "65f825e6147562cde0f14062",
  },
  {
    status: "active",
    name: {
      first: "Billy",
      middle: "Reese",
      last: "Okuneva",
    },
    username: "Billy-Okuneva",
    password: "Eyg2RARJi4WBCjB",
    emails: ["Eric84@gmail.com", "Emmanuelle7@gmail.com"],
    phoneNumber: "843-376-4515 x90862",
    location: {
      street: "111 Torphy Mount",
      city: "New Rethaworth",
      state: "Maryland",
      country: "Saint Kitts and Nevis",
      zip: "06754-3799",
      coordinates: {
        latitude: -36.0374,
        longitude: 87.5688,
      },
    },
    website: "https://unfolded-touch.biz/",
    domain: "menacing-drainage.info",
    job: {
      title: "National Functionality Architect",
      descriptor: "Dynamic",
      area: "Infrastructure",
      type: "Agent",
      company: "DuBuque - Crona",
    },
    creditCard: {
      number: "6011-6229-3974-6488-8490",
      cvv: "737",
      issuer: "visa",
    },
    uuid: "d4956ea5-f7c6-4485-8565-16d4998fca3e",
    objectId: "65f825e6147562cde0f14063",
  },
  {
    status: "active",
    name: {
      first: "Hobart",
      middle: "London",
      last: "Stark",
    },
    username: "Hobart-Stark",
    password: "oPitTULxFOo4gwf",
    emails: ["Adella.VonRueden47@example.com", "Anderson62@gmail.com"],
    phoneNumber: "296.411.7000 x2167",
    location: {
      street: "4930 Sauer Common",
      city: "Robelfurt",
      state: "Kentucky",
      country: "Saint Kitts and Nevis",
      zip: "05347",
      coordinates: {
        latitude: 15.4396,
        longitude: -8.6131,
      },
    },
    website: "https://energetic-alpenhorn.name",
    domain: "tremendous-skean.org",
    job: {
      title: "Legacy Accountability Facilitator",
      descriptor: "Internal",
      area: "Applications",
      type: "Supervisor",
      company: "Kuhlman, Hammes and Marvin",
    },
    creditCard: {
      number: "58936285785355269406",
      cvv: "980",
      issuer: "maestro",
    },
    uuid: "108267d0-e7bf-4914-b89d-9e89cc139e64",
    objectId: "65f825e6147562cde0f14064",
  },
  {
    status: "active",
    name: {
      first: "Frankie",
      middle: "Kai",
      last: "Upton",
    },
    username: "Frankie-Upton",
    password: "5W1iFRL4ouRzJt8",
    emails: ["Aubrey.Purdy96@example.com", "Demarco_Will33@example.com"],
    phoneNumber: "(317) 590-3636 x12843",
    location: {
      street: "658 Myrtice Forges",
      city: "Lake Clevelandchester",
      state: "South Dakota",
      country: "Central African Republic",
      zip: "04920",
      coordinates: {
        latitude: -28.2524,
        longitude: -79.9959,
      },
    },
    website: "https://creepy-bustle.net",
    domain: "pleased-heritage.biz",
    job: {
      title: "Forward Usability Facilitator",
      descriptor: "Future",
      area: "Directives",
      type: "Representative",
      company: "Schamberger Group",
    },
    creditCard: {
      number: "6771-8975-2649-6511",
      cvv: "631",
      issuer: "diners_club",
    },
    uuid: "8287294d-0df0-41dd-9276-e612b7f04a3e",
    objectId: "65f825e6147562cde0f14065",
  },
  {
    status: "active",
    name: {
      first: "Ivory",
      middle: "Hayden",
      last: "Gutkowski",
    },
    username: "Ivory-Gutkowski",
    password: "Ps7GXrXwr_2MRGj",
    emails: ["Jaiden_Wilkinson@gmail.com", "Suzanne_Nolan45@example.com"],
    phoneNumber: "(501) 807-1566",
    location: {
      street: "8595 Ernser Curve",
      city: "New Travis",
      state: "Maine",
      country: "Italy",
      zip: "64060-5838",
      coordinates: {
        latitude: 51.2177,
        longitude: 128.7869,
      },
    },
    website: "https://understated-c-clamp.info",
    domain: "trained-hurricane.net",
    job: {
      title: "Human Program Liaison",
      descriptor: "Dynamic",
      area: "Security",
      type: "Officer",
      company: "Haag, Christiansen and Runolfsdottir",
    },
    creditCard: {
      number: "6761-1131-1451-7417",
      cvv: "631",
      issuer: "diners_club",
    },
    uuid: "09f63524-ee7c-4611-9d21-942b9befe467",
    objectId: "65f825e6147562cde0f14066",
  },
  {
    status: "disabled",
    name: {
      first: "Gisselle",
      middle: "Rowan",
      last: "Waters",
    },
    username: "Gisselle-Waters",
    password: "5Mi5AOl4Vc8teoP",
    emails: ["Brandt_Howe@gmail.com", "Uriah22@example.com"],
    phoneNumber: "413.641.0651",
    location: {
      street: "4734 Brody Oval",
      city: "Naperville",
      state: "Mississippi",
      country: "Morocco",
      zip: "85640-9302",
      coordinates: {
        latitude: -11.6817,
        longitude: -110.7859,
      },
    },
    website: "https://squiggly-currency.org/",
    domain: "aromatic-plasterboard.biz",
    job: {
      title: "Corporate Interactions Engineer",
      descriptor: "International",
      area: "Integration",
      type: "Planner",
      company: "Kemmer, Roberts and Hills",
    },
    creditCard: {
      number: "5507-3017-6611-0448",
      cvv: "135",
      issuer: "jcb",
    },
    uuid: "0f92f9d8-31ed-42a8-a2aa-fc28e426d6d7",
    objectId: "65f825e6147562cde0f14067",
  },
  {
    status: "disabled",
    name: {
      first: "Sam",
      middle: "Kennedy",
      last: "Rogahn",
    },
    username: "Sam-Rogahn",
    password: "Ky250hma4xf9rcm",
    emails: ["Mathilde70@gmail.com", "Maxime.Prosacco@gmail.com"],
    phoneNumber: "(515) 906-9974 x58355",
    location: {
      street: "743 Vilma Plain",
      city: "East Donatochester",
      state: "North Carolina",
      country: "Spain",
      zip: "79223-3251",
      coordinates: {
        latitude: 37.5716,
        longitude: 56.4922,
      },
    },
    website: "https://wild-account.com/",
    domain: "grimy-feedback.com",
    job: {
      title: "Legacy Research Consultant",
      descriptor: "Principal",
      area: "Solutions",
      type: "Strategist",
      company: "Jakubowski - Sauer",
    },
    creditCard: {
      number: "3021-159546-2448",
      cvv: "049",
      issuer: "visa",
    },
    uuid: "ffd0d258-8e60-4021-91e4-cf0f07921de1",
    objectId: "65f825e6147562cde0f14068",
  },
  {
    status: "active",
    name: {
      first: "Lemuel",
      middle: "Rory",
      last: "Rogahn",
    },
    username: "Lemuel-Rogahn",
    password: "6E30UZ6UWy3qRTj",
    emails: ["Jett38@example.com", "Kaelyn31@example.com"],
    phoneNumber: "568.965.6947",
    location: {
      street: "873 Hirthe Park",
      city: "Fort Julieland",
      state: "Alabama",
      country: "Antigua and Barbuda",
      zip: "51273",
      coordinates: {
        latitude: 42.831,
        longitude: -72.6935,
      },
    },
    website: "https://valid-investigator.org",
    domain: "watery-work.net",
    job: {
      title: "Legacy Interactions Coordinator",
      descriptor: "Direct",
      area: "Tactics",
      type: "Producer",
      company: "Gutmann and Sons",
    },
    creditCard: {
      number: "5430-6564-0408-5746",
      cvv: "768",
      issuer: "jcb",
    },
    uuid: "2951befc-327e-46b1-8a51-921b4754fc17",
    objectId: "65f825e6147562cde0f14069",
  },
  {
    status: "active",
    name: {
      first: "Junior",
      middle: "Arden",
      last: "Johnston",
    },
    username: "Junior-Johnston",
    password: "BeEko1Z5jAfS5XZ",
    emails: ["Dawson75@gmail.com", "Trevor_Cremin@gmail.com"],
    phoneNumber: "1-780-945-1201 x78266",
    location: {
      street: "9449 Kertzmann Burg",
      city: "Paradise",
      state: "Tennessee",
      country: "Nigeria",
      zip: "08575",
      coordinates: {
        latitude: 51.551,
        longitude: 138.653,
      },
    },
    website: "https://worn-composer.name/",
    domain: "dutiful-homeownership.com",
    job: {
      title: "Corporate Accounts Representative",
      descriptor: "District",
      area: "Interactions",
      type: "Coordinator",
      company: "Buckridge - Stroman",
    },
    creditCard: {
      number: "6011-6271-6739-6732-3699",
      cvv: "275",
      issuer: "visa",
    },
    uuid: "113b7f15-dc99-402f-bb46-9d905468eabc",
    objectId: "65f825e6147562cde0f1406a",
  },
  {
    status: "active",
    name: {
      first: "Andreane",
      middle: "Kai",
      last: "Lehner",
    },
    username: "Andreane-Lehner",
    password: "gFUe_Sr6VUNveYZ",
    emails: ["Joelle55@example.com", "Hillary_Mertz@gmail.com"],
    phoneNumber: "1-685-725-5355 x585",
    location: {
      street: "27588 Fae Forest",
      city: "Fort Drake",
      state: "South Dakota",
      country: "Turkmenistan",
      zip: "14058-1224",
      coordinates: {
        latitude: 21.0766,
        longitude: -13.0682,
      },
    },
    website: "https://clueless-list.net/",
    domain: "harmful-limitation.net",
    job: {
      title: "Human Directives Specialist",
      descriptor: "Human",
      area: "Paradigm",
      type: "Planner",
      company: "McKenzie, Willms and Walker",
    },
    creditCard: {
      number: "3434-716522-02333",
      cvv: "919",
      issuer: "visa",
    },
    uuid: "7eb9bb5b-63a3-41dd-b73a-34d8fdd4291b",
    objectId: "65f825e6147562cde0f1406b",
  },
  {
    status: "disabled",
    name: {
      first: "Toby",
      middle: "Alex",
      last: "McCullough",
    },
    username: "Toby-McCullough",
    password: "ahySAWxTl_DMqPy",
    emails: ["Jaquelin_Renner78@gmail.com", "Melba_Nitzsche2@gmail.com"],
    phoneNumber: "786-220-8828 x0633",
    location: {
      street: "3676 Marjory Dam",
      city: "South Karianestad",
      state: "Alaska",
      country: "Ecuador",
      zip: "26466",
      coordinates: {
        latitude: 88.1503,
        longitude: -0.9106,
      },
    },
    website: "https://sophisticated-consistency.com",
    domain: "roasted-jumpsuit.net",
    job: {
      title: "Principal Security Orchestrator",
      descriptor: "Internal",
      area: "Applications",
      type: "Analyst",
      company: "Little - Cartwright",
    },
    creditCard: {
      number: "6759-7977-3518-0219",
      cvv: "407",
      issuer: "jcb",
    },
    uuid: "36815f36-5253-41eb-93e8-d5a50affb50a",
    objectId: "65f825e6147562cde0f1406c",
  },
  {
    status: "active",
    name: {
      first: "Gordon",
      middle: "Sage",
      last: "Brown",
    },
    username: "Gordon-Brown",
    password: "lNWDYTMwAT8ZRLY",
    emails: ["Bobby46@gmail.com", "Mckenna.Fisher@gmail.com"],
    phoneNumber: "1-762-479-3864",
    location: {
      street: "81305 Kuvalis Junctions",
      city: "Danbury",
      state: "Maryland",
      country: "Bhutan",
      zip: "16176",
      coordinates: {
        latitude: 15.0276,
        longitude: 89.9442,
      },
    },
    website: "https://sour-elimination.net/",
    domain: "impractical-toot.info",
    job: {
      title: "Chief Security Agent",
      descriptor: "Future",
      area: "Assurance",
      type: "Coordinator",
      company: "Jerde - Metz",
    },
    creditCard: {
      number: "4941517254828",
      cvv: "228",
      issuer: "discover",
    },
    uuid: "f09c503e-83f9-4e02-b6e8-2eded44b10ea",
    objectId: "65f825e6147562cde0f1406d",
  },
  {
    status: "disabled",
    name: {
      first: "Brody",
      middle: "Jules",
      last: "Spencer",
    },
    username: "Brody-Spencer",
    password: "4Qgg5hnbynKex1w",
    emails: ["Rossie90@example.com", "Wilbert_Nienow99@gmail.com"],
    phoneNumber: "1-707-472-1995 x445",
    location: {
      street: "852 Jovanny Isle",
      city: "Lake Deannaboro",
      state: "Pennsylvania",
      country: "Isle of Man",
      zip: "57945",
      coordinates: {
        latitude: 18.9051,
        longitude: 133.9375,
      },
    },
    website: "https://purple-inhibitor.name/",
    domain: "spectacular-foodstuffs.info",
    job: {
      title: "Investor Branding Supervisor",
      descriptor: "Dynamic",
      area: "Factors",
      type: "Supervisor",
      company: "Stoltenberg - Abshire",
    },
    creditCard: {
      number: "3529-4825-3997-1032",
      cvv: "188",
      issuer: "jcb",
    },
    uuid: "62fe212f-bdcc-458d-ad9b-e113f56860f8",
    objectId: "65f825e6147562cde0f1406e",
  },
  {
    status: "disabled",
    name: {
      first: "Adrienne",
      middle: "Skyler",
      last: "Dare",
    },
    username: "Adrienne-Dare",
    password: "1J9KSXIbwGsia5I",
    emails: ["Tyree.Bernier@example.com", "Arnoldo_Stehr@gmail.com"],
    phoneNumber: "(381) 866-0168 x16014",
    location: {
      street: "35921 Anabelle Ridge",
      city: "Fort Andre",
      state: "Alaska",
      country: "Chile",
      zip: "12268",
      coordinates: {
        latitude: 22.2501,
        longitude: -51.8567,
      },
    },
    website: "https://qualified-cheesecake.name/",
    domain: "radiant-duel.name",
    job: {
      title: "Legacy Program Manager",
      descriptor: "Product",
      area: "Factors",
      type: "Analyst",
      company: "Beatty - Buckridge",
    },
    creditCard: {
      number: "3529-6335-0629-8615",
      cvv: "361",
      issuer: "jcb",
    },
    uuid: "cbd72722-7663-406d-a0d3-d3eaa111a1b3",
    objectId: "65f825e6147562cde0f1406f",
  },
  {
    status: "active",
    name: {
      first: "Sabrina",
      middle: "Gray",
      last: "Heller",
    },
    username: "Sabrina-Heller",
    password: "5P0nyhMUFU8gE3W",
    emails: ["Janelle.Crona@gmail.com", "Marques82@gmail.com"],
    phoneNumber: "(331) 333-3558 x5459",
    location: {
      street: "95008 Sylvia Lakes",
      city: "South Kennatown",
      state: "Delaware",
      country: "Slovenia",
      zip: "93080-8036",
      coordinates: {
        latitude: 6.456,
        longitude: -94.4272,
      },
    },
    website: "https://unlawful-doing.com",
    domain: "gregarious-colonization.net",
    job: {
      title: "Global Factors Technician",
      descriptor: "Direct",
      area: "Quality",
      type: "Officer",
      company: "Schmitt - Larkin",
    },
    creditCard: {
      number: "4499951683044",
      cvv: "077",
      issuer: "maestro",
    },
    uuid: "2dede28d-18d6-4ce5-9deb-88bd9fdac9c5",
    objectId: "65f825e6147562cde0f14070",
  },
  {
    status: "active",
    name: {
      first: "Marge",
      middle: "Kyle",
      last: "Schneider",
    },
    username: "Marge-Schneider",
    password: "C4l7CLz4hamsvgO",
    emails: ["Aletha_Harvey69@gmail.com", "Bulah.Morissette@example.com"],
    phoneNumber: "786-758-6065 x33948",
    location: {
      street: "8693 Theron Parkway",
      city: "Harrisburg",
      state: "Illinois",
      country: "Senegal",
      zip: "73724-9213",
      coordinates: {
        latitude: 49.6641,
        longitude: -84.1268,
      },
    },
    website: "https://deserted-ambassador.name",
    domain: "fearless-boyfriend.org",
    job: {
      title: "Future Marketing Officer",
      descriptor: "Future",
      area: "Creative",
      type: "Facilitator",
      company: "Stroman, Beier and Brown",
    },
    creditCard: {
      number: "5347-6062-4177-5415",
      cvv: "960",
      issuer: "maestro",
    },
    uuid: "2210eefd-eb0e-4f6c-8889-3c239ff95282",
    objectId: "65f825e6147562cde0f14071",
  },
  {
    status: "disabled",
    name: {
      first: "Oleta",
      middle: "Sage",
      last: "Hermann",
    },
    username: "Oleta-Hermann",
    password: "gffojb31FBNidb9",
    emails: ["Reina.Grant@gmail.com", "Elvis_Pfeffer33@example.com"],
    phoneNumber: "1-504-756-6316 x79611",
    location: {
      street: "1442 William Forest",
      city: "Lueilwitzstad",
      state: "Arkansas",
      country: "Iraq",
      zip: "22758-8020",
      coordinates: {
        latitude: -3.9094,
        longitude: -11.7445,
      },
    },
    website: "https://clear-check.biz/",
    domain: "glaring-continent.net",
    job: {
      title: "Corporate Factors Designer",
      descriptor: "National",
      area: "Infrastructure",
      type: "Orchestrator",
      company: "Wolf LLC",
    },
    creditCard: {
      number: "3528-1781-3333-2560",
      cvv: "051",
      issuer: "maestro",
    },
    uuid: "a4bea9b7-0e23-47be-9fe1-ca9c2aef88b6",
    objectId: "65f825e6147562cde0f14072",
  },
  {
    status: "disabled",
    name: {
      first: "Cade",
      middle: "River",
      last: "Schulist",
    },
    username: "Cade-Schulist",
    password: "AbObC6zHR1ZcfL4",
    emails: ["Melvin.Schimmel25@gmail.com", "Agustina4@gmail.com"],
    phoneNumber: "671.436.5316 x90054",
    location: {
      street: "5171 Rosalyn Plains",
      city: "East Alisonborough",
      state: "Pennsylvania",
      country: "Turkmenistan",
      zip: "24360",
      coordinates: {
        latitude: 55.764,
        longitude: -47.7468,
      },
    },
    website: "https://treasured-sunday.org/",
    domain: "stark-bicycle.biz",
    job: {
      title: "Forward Group Engineer",
      descriptor: "Human",
      area: "Marketing",
      type: "Director",
      company: "Labadie, Brekke and Casper",
    },
    creditCard: {
      number: "3045-470500-9432",
      cvv: "390",
      issuer: "diners_club",
    },
    uuid: "5c1e2686-b857-42ba-9a75-fa4cb868a985",
    objectId: "65f825e6147562cde0f14073",
  },
  {
    status: "active",
    name: {
      first: "Mackenzie",
      middle: "Jamie",
      last: "Lang",
    },
    username: "Mackenzie-Lang",
    password: "xDW7Lax0YUDYRvn",
    emails: ["Laney.Connelly@example.com", "Kenna51@example.com"],
    phoneNumber: "554.881.3282",
    location: {
      street: "9148 Keeley Lock",
      city: "Bernhardberg",
      state: "Minnesota",
      country: "Madagascar",
      zip: "34516",
      coordinates: {
        latitude: 84.8007,
        longitude: -89.9451,
      },
    },
    website: "https://hefty-use.com/",
    domain: "lively-disadvantage.biz",
    job: {
      title: "District Configuration Liaison",
      descriptor: "Legacy",
      area: "Accounts",
      type: "Developer",
      company: "Berge - Bartoletti",
    },
    creditCard: {
      number: "3437-851901-26856",
      cvv: "485",
      issuer: "maestro",
    },
    uuid: "6f50b04b-778b-4bdc-9b24-d0c76db9fc2c",
    objectId: "65f825e6147562cde0f14074",
  },
  {
    status: "active",
    name: {
      first: "Kaleigh",
      middle: "Emerson",
      last: "Weissnat-Koelpin",
    },
    username: "Kaleigh-Weissnat-Koelpin",
    password: "9MgXTQ7uFqFExoT",
    emails: ["Maurice.Gerlach12@gmail.com", "Clemmie_Harvey@example.com"],
    phoneNumber: "1-307-981-0313 x725",
    location: {
      street: "87357 Fidel Creek",
      city: "South Lianahaven",
      state: "New Jersey",
      country: "Kuwait",
      zip: "75007-3738",
      coordinates: {
        latitude: 40.8657,
        longitude: -50.726,
      },
    },
    website: "https://moist-linguistics.org",
    domain: "parched-ethics.net",
    job: {
      title: "Chief Identity Officer",
      descriptor: "Human",
      area: "Intranet",
      type: "Designer",
      company: "Renner - Koss",
    },
    creditCard: {
      number: "5403-5969-4523-2014",
      cvv: "240",
      issuer: "maestro",
    },
    uuid: "20e51bfe-a650-4484-a20f-8e82c497b11d",
    objectId: "65f825e6147562cde0f14075",
  },
  {
    status: "active",
    name: {
      first: "Tamia",
      middle: "Shiloh",
      last: "Swift",
    },
    username: "Tamia-Swift",
    password: "QeMM6rkDfgQf9mc",
    emails: ["Kaleb_Skiles@gmail.com", "Jakayla_Hettinger32@example.com"],
    phoneNumber: "(809) 338-2810 x5806",
    location: {
      street: "9220 Hirthe Fords",
      city: "East Janelle",
      state: "Connecticut",
      country: "South Georgia and the South Sandwich Islands",
      zip: "17824-6742",
      coordinates: {
        latitude: 50.7821,
        longitude: -112.7174,
      },
    },
    website: "https://whispered-kite.org/",
    domain: "well-off-diarist.com",
    job: {
      title: "Corporate Interactions Facilitator",
      descriptor: "Chief",
      area: "Factors",
      type: "Representative",
      company: "Hills, Grant and Waters",
    },
    creditCard: {
      number: "6304927975532304",
      cvv: "583",
      issuer: "american_express",
    },
    uuid: "78c77793-3029-4e38-a764-830fb18f3135",
    objectId: "65f825e6147562cde0f14076",
  },
  {
    status: "disabled",
    name: {
      first: "Makayla",
      middle: "Anderson",
      last: "Leuschke",
    },
    username: "Makayla-Leuschke",
    password: "pGubvo_VTeONA2o",
    emails: ["Zena.Luettgen@example.com", "Abigail.Stroman52@example.com"],
    phoneNumber: "214-938-1404 x592",
    location: {
      street: "6619 Phoebe Flats",
      city: "Murfreesboro",
      state: "Washington",
      country: "Thailand",
      zip: "70625-5067",
      coordinates: {
        latitude: 47.146,
        longitude: 142.3926,
      },
    },
    website: "https://green-manager.com/",
    domain: "muted-beret.biz",
    job: {
      title: "Senior Brand Orchestrator",
      descriptor: "Chief",
      area: "Usability",
      type: "Facilitator",
      company: "Hansen LLC",
    },
    creditCard: {
      number: "5893018771134906",
      cvv: "133",
      issuer: "diners_club",
    },
    uuid: "e68b3ec3-a51a-4740-bcab-09fe7a5206a6",
    objectId: "65f825e6147562cde0f14077",
  },
];

export const states = users
  .map((u) => u.location.state)
  .filter((v, i, a) => a.indexOf(v) === i);
