import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";

const packagesDir = fileURLToPath(new URL("../../../", import.meta.url));
const target = fileURLToPath(
  new URL("../../src/flowPackages.generated.ts", import.meta.url),
);

/**
 * Emits the names of every published workspace package.
 *
 * Derived, not maintained: `upgrade` has to move every Flow-line dependency the
 * consumer has, because they share one version and declare exact peers on each
 * other. A hand-written list would silently miss a new package.
 *
 * `@mittwald/flow-codemods` itself is excluded by name: it is published too, so
 * the glob would otherwise list it, but the CLI does not upgrade itself — `npx`
 * always fetches the current version.
 */
export const generateFlowPackages = async (): Promise<void> => {
  const names = readdirSync(packagesDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .flatMap((entry) => {
      const manifestPath = join(packagesDir, entry.name, "package.json");
      try {
        const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
          name?: string;
          private?: boolean | string;
        };
        // `private` shows up as the string "true" as well as the boolean
        // (packages/core), matching the check `.github/scripts/version-contract-lib.mjs`
        // already uses for the same distinction.
        return manifest.private === true ||
          manifest.private === "true" ||
          manifest.name === undefined ||
          manifest.name === "@mittwald/flow-codemods"
          ? []
          : [manifest.name];
      } catch {
        return [];
      }
    })
    .toSorted();

  const source = [
    "// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.",
    "//",
    "// Source: the non-private packages of packages/*",
    "",
    "/** Every package published from the Flow monorepo, which all share one version. */",
    `export const flowPackages: string[] = ${JSON.stringify(names, null, 2)};`,
  ].join("\n");

  const prettierConfig = await resolveConfig(target);
  await writeFile(
    target,
    await format(source, { ...prettierConfig, parser: "typescript" }),
    "utf8",
  );
};
