import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { rcompare } from "semver";
import { readCatalog } from "../../src/catalog/read";

const target = fileURLToPath(
  new URL("../../src/migrations.generated.ts", import.meta.url),
);

/**
 * Emits the catalogue as a typed module.
 *
 * A module rather than JSON so `tsc` compiles it into `dist` like any other
 * file — no JSON copying to get right — and so the frontmatter is type-checked
 * against `MigrationEntry` on every `test:compile`.
 *
 * The body is dropped: it is prose for humans, it is the largest part of the
 * catalogue, and the CLI never prints it. `list` shows `apply` and `verify`.
 */
export const generateMigrationsModule = async (): Promise<void> => {
  const entries = readCatalog()
    .toSorted((a, b) => rcompare(a.since, b.since))
    .map(({ body: _body, ...rest }) => rest);

  const source = [
    "// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.",
    "//",
    "// Source: packages/codemods/src/migrations/*.md",
    "",
    'import type { MigrationEntry } from "./catalog/types.js";',
    "",
    "/** Every migration, newest first. Bodies live in `src/migrations`. */",
    'export const migrations: Omit<MigrationEntry, "body">[] =',
    `  ${JSON.stringify(entries, null, 2)};`,
  ].join("\n");

  const prettierConfig = await resolveConfig(target);
  await writeFile(
    target,
    await format(source, { ...prettierConfig, parser: "typescript" }),
    "utf8",
  );
};
