import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { readCatalog } from "../../src/catalog/read";
import { compareSince } from "../../src/catalog/unreleased";

const target = fileURLToPath(
  new URL("../../src/migrations.generated.ts", import.meta.url),
);

/**
 * Emits the catalogue as a typed module.
 *
 * A module rather than JSON so `tsc` compiles it into `dist` like any other
 * file — no JSON copying to get right — and so the frontmatter is type-checked
 * against `MigrationEntry` on every `test:compile`.
 *
 * The body is dropped: it is prose for humans, it is the largest part of the
 * catalogue, and the CLI never prints it. `list` shows `apply`.
 */
export const generateMigrationsModule = async (): Promise<void> => {
  // The `id` tie-break is not decoration: several releases carry two entries
  // (`0.2.0-alpha.646`, `.846` and `.1005` each have two), and without it their
  // order falls back to `readdirSync`, whose order Node does not guarantee
  // across platforms. The generated file would then differ between machines and
  // fail CI's `git diff --exit-code`.
  const entries = readCatalog()
    // `compareSince` reversed, rather than `semver.rcompare`: an entry still on
    // the `UNRELEASED` placeholder has no comparable version, and rcompare
    // throws on it (#2890).
    .toSorted(
      (a, b) => compareSince(b.since, a.since) || a.id.localeCompare(b.id),
    )
    .map(({ body: ignoredBody, ...rest }) => rest);

  const source = [
    "// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.",
    "//",
    "// Source: packages/codemods/src/migrations/<id>/entry.md",
    "",
    'import type { MigrationEntry } from "./catalog/types.js";',
    "",
    "/** Every migration, newest first. Bodies live in `src/migrations`. */",
    'export const migrations: Omit<MigrationEntry, "body">[] =',
    `  ${JSON.stringify(entries, null, 2)};`,
  ].join("\n");

  const prettierConfig = await resolveConfig(target);
  await writeFile(
    target,
    await format(source, { ...prettierConfig, parser: "typescript" }),
    "utf8",
  );
};
