import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import { rcompare } from "semver";
import { readCatalog } from "../../src/catalog/read";
import type { MigrationEntry } from "../../src/catalog/types";

const target = fileURLToPath(
  new URL("../../../components/MIGRATION.md", import.meta.url),
);

const intro = `# Migrations

<!-- AUTO-GENERATED by \`pnpm nx build codemods\` — do not edit.
     Source: packages/codemods/src/migrations/<id>/entry.md -->

Entries are sorted by version, newest first. Find the version you are coming
from and work your way up.

Catching up across several versions? One command bumps every Flow dependency and
runs the codemod of every migration up to the version it lands on:

\`\`\`shell
npx @mittwald/flow-codemods@latest upgrade
\`\`\`

It is not the whole migration. Most entries below have no codemod and have to be
done by hand — the command prints those when it is done. It lists migrations
older than your current version too: nothing records which ones you already
performed, and re-running a codemod is a no-op.

It refuses to run on a dirty working tree (\`--allow-dirty\` overrides that) and
rewrites files in place, so review the diff afterwards.

Every command on this page is written with \`npx\`, because a generated file
cannot know your package manager. Substitute the equivalent if yours differs:
\`pnpm dlx\`, \`yarn dlx\` (Yarn Classic has no \`dlx\` — it uses \`npx\`), or
\`bun x\`. The CLI's own output does detect it and prints the right form.
`;

const remoteNote = "also applies to `@mittwald/flow-remote-react-components`";

const renderEntry = (entry: MigrationEntry): string => {
  const facts = [
    `**Since \`${entry.since}\`**`,
    entry.kind,
    entry.action === "codemod"
      ? "codemod available"
      : entry.action === "manual"
        ? "manual change"
        : "no code change needed",
    entry.remotePackage ? remoteNote : undefined,
  ].filter((fact) => fact !== undefined);

  const invocation =
    entry.action === "codemod"
      ? // `src` and `npx` are both assumptions a generated file has to make —
        // see the note in `intro`. The CLI prints the detected form instead.
        `\`\`\`shell\nnpx @mittwald/flow-codemods@latest ${entry.id} src\n\`\`\`\n`
      : "";

  return [
    `<a id="${entry.id}"></a>`,
    "",
    `## ${entry.title}`,
    "",
    facts.join(" · "),
    "",
    entry.body,
    "",
    `**Apply:** ${entry.apply}`,
    "",
    invocation,
  ].join("\n");
};

/** The guide as source, so a test can compare without writing anything. */
export const renderMigrationGuide = async (): Promise<string> => {
  const entries = readCatalog()
    // Same `id` tie-break as the generated module, and for the same reason:
    // duplicate `since` values would otherwise order by directory listing.
    .toSorted((a, b) => rcompare(a.since, b.since) || a.id.localeCompare(b.id));

  const markdown = [intro, ...entries.map(renderEntry)].join("\n---\n\n");

  const prettierConfig = await resolveConfig(target);
  return format(markdown, { ...prettierConfig, parser: "markdown" });
};

export const generateMigrationGuide = async (): Promise<void> => {
  await writeFile(target, await renderMigrationGuide(), "utf8");
};
