import { renderRemoteTest } from "@/tests/renderRemoteTest";
import { expect, test } from "vitest";

test("AreaChart is rendered", async () => {
  const dom = renderRemoteTest("standard");
  const areaChart = dom.getByTestId("areaChart");
  await expect.element(areaChart).toBeInTheDocument();
  expect(areaChart.element()).toMatchInlineSnapshot(`
    <svg
      class="recharts-surface"
      data-testid="areaChart"
      height="200"
      role="application"
      style="width: 100%; height: 100%;"
      tabindex="0"
      viewBox="0 0 414 200"
      width="414"
    >
      <title />
      <desc />
      <defs>
        <clippath
          id="recharts1-clip"
        >
          <rect
            height="160"
            width="344"
            x="65"
            y="5"
          />
        </clippath>
      </defs>
      <g
        class="recharts-layer recharts-area"
      >
        <defs>
          <clippath
            id="clipPath-recharts-area-2"
          >
            <rect
              height="160"
              width="688"
              x="-107"
              y="5"
            />
          </clippath>
        </defs>
        <g
          class="recharts-layer"
        >
          <defs>
            <clippath
              id="animationClipPath-recharts-area-2"
            >
              <rect
                height="166"
                width="0"
                x="65"
                y="0"
              />
            </clippath>
          </defs>
          <g
            class="recharts-layer"
            clip-path="url(#animationClipPath-recharts-area-2)"
          >
            <g
              class="recharts-layer"
              clip-path="url(#clipPath-recharts-area-2)"
            >
              <path
                class="recharts-curve recharts-area-area"
                d="M65,-155L409,-75L409,165L65,165Z"
                fill="none"
                fill-opacity="1"
                height="160"
                stroke="none"
                width="344"
              />
            </g>
          </g>
        </g>
      </g>
      <g
        class="recharts-layer recharts-cartesian-axis recharts-xAxis xAxis"
      >
        <line
          class="recharts-cartesian-axis-line"
          fill="none"
          font-size="0.875rem"
          height="30"
          orientation="bottom"
          stroke="#666"
          width="344"
          x="65"
          x1="65"
          x2="409"
          y="165"
          y1="165"
          y2="165"
        />
        <g
          class="recharts-cartesian-axis-ticks"
        >
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="30"
              orientation="bottom"
              stroke="#666"
              width="344"
              x="65"
              x1="65"
              x2="65"
              y="165"
              y1="173"
              y2="165"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="30"
              orientation="bottom"
              stroke="none"
              text-anchor="middle"
              width="344"
              x="65"
              y="181"
            >
              <tspan
                dy="0.71em"
                x="65"
              >
                Stat 1
              </tspan>
            </text>
          </g>
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="30"
              orientation="bottom"
              stroke="#666"
              width="344"
              x="65"
              x1="409"
              x2="409"
              y="165"
              y1="173"
              y2="165"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="30"
              orientation="bottom"
              stroke="none"
              text-anchor="middle"
              width="344"
              x="397.859375"
              y="181"
            >
              <tspan
                dy="0.71em"
                x="397.859375"
              >
                Stat 2
              </tspan>
            </text>
          </g>
        </g>
      </g>
      <g
        class="recharts-layer recharts-cartesian-axis recharts-yAxis yAxis"
      >
        <line
          class="recharts-cartesian-axis-line"
          fill="none"
          font-size="0.875rem"
          height="160"
          orientation="left"
          stroke="#666"
          width="60"
          x="5"
          x1="65"
          x2="65"
          y="5"
          y1="5"
          y2="165"
        />
        <g
          class="recharts-cartesian-axis-ticks"
        >
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="#666"
              width="60"
              x="5"
              x1="57"
              x2="65"
              y="5"
              y1="165"
              y2="165"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="none"
              text-anchor="end"
              width="60"
              x="49"
              y="165"
            >
              <tspan
                dy="0.355em"
                x="49"
              >
                0
              </tspan>
            </text>
          </g>
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="#666"
              width="60"
              x="5"
              x1="57"
              x2="65"
              y="5"
              y1="125"
              y2="125"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="none"
              text-anchor="end"
              width="60"
              x="49"
              y="125"
            >
              <tspan
                dy="0.355em"
                x="49"
              >
                5
              </tspan>
            </text>
          </g>
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="#666"
              width="60"
              x="5"
              x1="57"
              x2="65"
              y="5"
              y1="85"
              y2="85"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="none"
              text-anchor="end"
              width="60"
              x="49"
              y="85"
            >
              <tspan
                dy="0.355em"
                x="49"
              >
                10
              </tspan>
            </text>
          </g>
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="#666"
              width="60"
              x="5"
              x1="57"
              x2="65"
              y="5"
              y1="45"
              y2="45"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="none"
              text-anchor="end"
              width="60"
              x="49"
              y="45"
            >
              <tspan
                dy="0.355em"
                x="49"
              >
                15
              </tspan>
            </text>
          </g>
          <g
            class="recharts-layer recharts-cartesian-axis-tick"
          >
            <line
              class="recharts-cartesian-axis-tick-line"
              fill="none"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="#666"
              width="60"
              x="5"
              x1="57"
              x2="65"
              y="5"
              y1="5"
              y2="5"
            />
            <text
              class="recharts-text recharts-cartesian-axis-tick-value"
              fill="#222222"
              font-size="0.875rem"
              height="160"
              orientation="left"
              stroke="none"
              text-anchor="end"
              width="60"
              x="49"
              y="8.5"
            >
              <tspan
                dy="0.355em"
                x="49"
              >
                20
              </tspan>
            </text>
          </g>
        </g>
      </g>
    </svg>
  `);
});
