name: General Style Guide Feedback
description: Share general or specific feedback regarding the style guide.
title: "General Feedback"
labels: ["feedback"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your feedback! Please let us know what kind of project you're working on and what you'd like to share.

  - type: input
    id: project-type
    attributes:
      label: Project Information
      description: What type of project are you working on? (e.g., an mStudio extension, a custom app, etc.)
      placeholder: e.g. mStudio extension, own project, etc.
    validations:
      required: false

  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: What would you like to share with us? General feedback or something about a specific area?
      placeholder: Write your feedback here…
    validations:
      required: true
