export const demoData = [
  {
    name: "Adeel Solangi",
    language: "Sindhi",
    id: "V59OF92YF627HFY0",
    bio: "Donec lobortis eleifend condimentum. Cras dictum dolor lacinia lectus vehicula rutrum. Maecenas quis nisi nunc. Nam tristique feugiat est vitae mollis. Maecenas quis nisi nunc.",
    version: 6.1,
    birthdate: "1985-06-14T00:00:00.000Z",
  },
  {
    name: "Afzal Ghaffar",
    language: "Sindhi",
    id: "ENTOCR13RSCLZ6KU",
    bio: "Aliquam sollicitudin ante ligula, eget malesuada nibh efficitur et. Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Etiam congue dignissim volutpat. Vestibulum pharetra libero et velit gravida euismod.",
    version: 1.88,
    birthdate: "1992-03-22T00:00:00.000Z",
  },
  {
    name: "Aamir Solangi",
    language: "Sindhi",
    id: "IAKPO3R4761JDRVG",
    bio: "Vestibulum pharetra libero et velit gravida euismod. Quisque mauris ligula, efficitur porttitor sodales ac, lacinia non ex. Fusce eu ultrices elit, vel posuere neque.",
    version: 7.27,
    birthdate: "1988-11-05T00:00:00.000Z",
  },
  {
    name: "Abla Dilmurat",
    language: "Uyghur",
    id: "5ZVOEPMJUI4MB4EN",
    bio: "Donec lobortis eleifend condimentum. Morbi ac tellus erat.",
    version: 2.53,
    birthdate: "1978-08-19T00:00:00.000Z",
  },
  {
    name: "Adil Eli",
    language: "Uyghur",
    id: "6VTI8X6LL0MMPJCC",
    bio: "Vivamus id faucibus velit, id posuere leo. Morbi vitae nisi lacinia, laoreet lorem nec, egestas orci. Suspendisse potenti.",
    version: 6.49,
    birthdate: "1990-12-03T00:00:00.000Z",
  },
  {
    name: "Adile Qadir",
    language: "Uyghur",
    id: "F2KEU5L7EHYSYFTT",
    bio: "Duis commodo orci ut dolor iaculis facilisis. Morbi ultricies consequat ligula posuere eleifend. Aenean finibus in tortor vel aliquet. Fusce eu ultrices elit, vel posuere neque.",
    version: 1.9,
    birthdate: "1983-05-27T00:00:00.000Z",
  },
  {
    name: "Abdukerim Ibrahim",
    language: "Uyghur",
    id: "LO6DVTZLRK68528I",
    bio: "Vivamus id faucibus velit, id posuere leo. Nunc aliquet sodales nunc a pulvinar. Nunc aliquet sodales nunc a pulvinar. Ut viverra quis eros eu tincidunt.",
    version: 5.9,
    birthdate: "1987-09-14T00:00:00.000Z",
  },
  {
    name: "Adil Abro",
    language: "Sindhi",
    id: "LJRIULRNJFCNZJAJ",
    bio: "Etiam malesuada blandit erat, nec ultricies leo maximus sed. Fusce congue aliquam elit ut luctus. Etiam malesuada blandit erat, nec ultricies leo maximus sed. Cras dictum dolor lacinia lectus vehicula rutrum. Integer vehicula, arcu sit amet egestas efficitur, orci justo interdum massa, eget ullamcorper risus ligula tristique libero.",
    version: 9.32,
    birthdate: "1981-07-30T00:00:00.000Z",
  },
  {
    name: "Afonso Vilarchán",
    language: "Galician",
    id: "JMCL0CXNXHPL1GBC",
    bio: "Fusce eu ultrices elit, vel posuere neque. Morbi ac tellus erat. Nunc tincidunt laoreet laoreet.",
    version: 5.21,
    birthdate: "1994-02-16T00:00:00.000Z",
  },
  {
    name: "Mark Schembri",
    language: "Maltese",
    id: "KU4T500C830697CW",
    bio: "Nam laoreet, nunc non suscipit interdum, justo turpis vestibulum massa, non vulputate ex urna at purus. Morbi ultricies consequat ligula posuere eleifend. Vivamus id faucibus velit, id posuere leo. Sed laoreet posuere sapien, ut feugiat nibh gravida at. Ut maximus, libero nec facilisis fringilla, ex sem sollicitudin leo, non congue tortor ligula in eros.",
    version: 3.17,
    birthdate: "1989-10-12T00:00:00.000Z",
  },
  {
    name: "Antía Sixirei",
    language: "Galician",
    id: "XOF91ZR7MHV1TXRS",
    bio: "Pellentesque massa sem, scelerisque sit amet odio id, cursus tempor urna. Phasellus massa ligula, hendrerit eget efficitur eget, tincidunt in ligula. Morbi finibus dui sed est fringilla ornare. Duis pellentesque ultrices convallis. Morbi ultricies consequat ligula posuere eleifend.",
    version: 6.44,
    birthdate: "1982-04-06T00:00:00.000Z",
  },
];
