import { createFlowRemoteComponentRenderer } from "@/lib/createFlowRemoteComponentRenderer";
import { elementFactory } from "@/lib/elementFactory";
import { createRemoteComponentRenderer } from "@mittwald/remote-dom-react/host";
import autoGenerated from "./auto-generated";
import { Form, SlotRootWrapper, TunnelEntry } from "@/components/";
import { NotificationRenderController } from "@/components/NotificationRenderController";

const htmlComponentsMap = {
  svg: createRemoteComponentRenderer(elementFactory("svg")),
  circle: createRemoteComponentRenderer(elementFactory("circle")),
  g: createRemoteComponentRenderer(elementFactory("g")),
  path: createRemoteComponentRenderer(elementFactory("path")),
  strong: createRemoteComponentRenderer(elementFactory("strong")),
  ul: createRemoteComponentRenderer(elementFactory("ul")),
  ol: createRemoteComponentRenderer(elementFactory("ol")),
  li: createRemoteComponentRenderer(elementFactory("li")),
} as const;

/**
 * Components that are allowed to be used remotely but should not be rendered on
 * the host.
 */
const skippedComponentsMap = {
  script: () => null,
} as const;

const flowComponentsMap = {
  "flr-form": createFlowRemoteComponentRenderer("Form", Form),
  "flr-slot-root-wrapper": createFlowRemoteComponentRenderer(
    "SlotRootWrapper",
    SlotRootWrapper,
  ),
  "flr-notification": createFlowRemoteComponentRenderer(
    "Notification",
    NotificationRenderController,
  ),
  "flr-tunnel-entry": createFlowRemoteComponentRenderer(
    "TunnelEntry",
    TunnelEntry,
  ),
};

export const components = {
  ...htmlComponentsMap,
  ...skippedComponentsMap,
  ...autoGenerated,
  ...flowComponentsMap,
};
