import { createFlowRemoteComponentRenderer } from "@/lib/createFlowRemoteComponentRenderer";
import { elementFactory } from "@/lib/elementFactory";
import { createRemoteComponentRenderer } from "@mfalkenberg/remote-dom-react/host";
import autoGenerated from "./auto-generated";
import { Form, SlotRootWrapper } from "@/components/";

const htmlComponentsMap = {
  svg: createRemoteComponentRenderer(elementFactory("svg")),
  circle: createRemoteComponentRenderer(elementFactory("circle")),
  g: createRemoteComponentRenderer(elementFactory("g")),
  path: createRemoteComponentRenderer(elementFactory("path")),
  strong: createRemoteComponentRenderer(elementFactory("strong")),
} as const;

const flowComponentsMap = {
  "flr-form": createFlowRemoteComponentRenderer(Form),
  "flr-slot-root-wrapper": createFlowRemoteComponentRenderer(SlotRootWrapper),
};

export const components = {
  ...htmlComponentsMap,
  ...flowComponentsMap,
  ...autoGenerated,
};
