// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.
//
// Source: the non-private packages of packages/*

/** Every package published from the Flow monorepo, which all share one version. */
export const flowPackages: string[] = [
  "@mittwald/ext-bridge",
  "@mittwald/flow-design-tokens",
  "@mittwald/flow-icons",
  "@mittwald/flow-icons-pro",
  "@mittwald/flow-react-components",
  "@mittwald/flow-remote-core",
  "@mittwald/flow-remote-elements",
  "@mittwald/flow-remote-react-components",
  "@mittwald/flow-remote-react-renderer",
  "@mittwald/flow-stylesheet",
  "@mittwald/mstudio-ext-react-components",
  "@mittwald/react-tunnel",
];
