// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.
//
// Source: packages/codemods/src/migrations/*.md

import type { MigrationEntry } from "./catalog/types.js";

/** Every migration, newest first. Bodies live in `src/migrations`. */
export const migrations: Omit<MigrationEntry, "body">[] = [
  {
    id: "align-to-combine",
    since: "0.2.0-alpha.1047",
    title: "Align renamed to Combine",
    kind: "migration",
    action: "codemod",
    remotePackage: true,
    detect: "rg -t ts -t tsx '\\bAlign(Props)?\\b'",
    apply:
      "Rename `Align` to `Combine` and `AlignProps` to `CombineProps`, for named, aliased and namespace imports from a Flow package.",
    verify: "tsc --noEmit passes, and `rg '\\bAlign\\b'` finds no Flow import.",
  },
  {
    id: "renamed-css-export",
    since: "0.1.0-alpha.292",
    title: "Renamed CSS export",
    kind: "migration",
    action: "manual",
    remotePackage: false,
    detect: "rg 'flow-react-components/styles'",
    apply:
      "Replace the import `@mittwald/flow-react-components/styles` with `@mittwald/flow-react-components/all.css`.",
    verify:
      "The bundle builds and the stylesheet is present; `rg 'flow-react-components/styles'` finds nothing.",
  },
];
