// AUTO-GENERATED by `pnpm nx build codemods` — do not edit.
//
// Source: packages/codemods/src/migrations/*.md

import type { MigrationEntry } from "./catalog/types.js";

/** Every migration, newest first. Bodies live in `src/migrations`. */
export const migrations: Omit<MigrationEntry, "body">[] = [
  {
    id: "segmented-control-deprecated",
    since: "0.2.0-alpha.1056",
    title: "SegmentedControl deprecated",
    kind: "deprecation",
    action: "manual",
    remotePackage: true,
    apply:
      "Replace `SegmentedControl` with `Tabs` when the selection switches displayed content, or with `RadioGroup` when it sets a value. Pick per usage — this is a structural change, not a rename.",
  },
  {
    id: "align-to-combine",
    since: "0.2.0-alpha.1047",
    title: "Align renamed to Combine",
    kind: "migration",
    action: "codemod",
    remotePackage: true,
    apply:
      "Rename `Align` to `Combine` and `AlignProps` to `CombineProps`, for named, aliased and namespace imports from a Flow package.",
  },
  {
    id: "button-color-accent-to-success",
    since: "0.2.0-alpha.1046",
    title: "Button: color `accent` renamed to `success`",
    kind: "migration",
    action: "codemod",
    remotePackage: true,
    apply:
      'Rename `color="accent"` to `color="success"` on `Button` and `SubmitButton`. Also update the CSS class `flow--button--accent` to `flow--button--success` and every `--button--accent-{solid,plain,soft,outline}-*` design token to its `success` counterpart if you use `@mittwald/flow-stylesheet` or the token CSS variables directly — those have no fallback.',
  },
  {
    id: "tooltip-trigger-delay-type",
    since: "0.2.0-alpha.1016",
    title: "TooltipTrigger changed delay type",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      'Replace every numeric `delay` value on `TooltipTrigger` with one of the two string literals: `"default"` (400ms) or `"long"` (1500ms). Pick by intent, not by which number is closer — `"default"` is for elements that cannot be understood without the tooltip (icon-only buttons), `"long"` is for supplementary information on elements that are already labeled. A previous numeric value is not a reliable guide: `delay={500}` maps to `"default"` (400ms), not `"long"` (1500ms), if the element still needs the tooltip to be understood.',
  },
  {
    id: "flags-to-component-defaults-provider",
    since: "0.2.0-alpha.1005",
    title: "`flags` is replaced by the ComponentDefaultsProvider",
    kind: "deprecation",
    action: "manual",
    remotePackage: false,
    apply:
      "Replace assignments to the global `flags` object with an equivalent `<ComponentDefaultsProvider defaults={{ ... }} />` wrapping the app, or the subtree the default should apply to.",
  },
  {
    id: "modal-unsaved-changes-confirmation",
    since: "0.2.0-alpha.1005",
    title: "Closing a Modal with unsaved changes is confirmed by default",
    kind: "migration",
    action: "none",
    remotePackage: true,
    apply:
      "No code change required — if you had `requireCloseModalConfirmationOnUnsavedChanges` enabled, the new default matches it. To keep the previous behaviour (closing without confirmation), set `Form: { confirmModalCloseOnUnsavedChanges: false }` via `<ComponentDefaultsProvider />`, or its deprecated equivalent, the `flags.requireCloseModalConfirmationOnUnsavedChanges = false` assignment.",
  },
  {
    id: "table-column-width-props",
    since: "0.2.0-alpha.956",
    title: "TableColumn: `maxWidth` removed, `width` and `minWidth` retyped",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "Remove `maxWidth` from every `TableColumn`. Where `width` or `minWidth` was `null`, omit the prop instead — the type no longer accepts `null`, only `number | string`.",
  },
  {
    id: "table-render-prop-removed",
    since: "0.2.0-alpha.866",
    title: "Table: `render` prop removed",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "Replace the `render` escape hatch on `Table` with a composition of `TableHeader`, `TableColumn`, `TableBody`, `TableRow` and `TableCell`.",
  },
  {
    id: "color-primary-to-default",
    since: "0.2.0-alpha.846",
    title:
      'Breadcrumb, HeaderNavigation, Heading, IllustratedMessage, and Link: color property "primary" renamed to "default"',
    kind: "migration",
    action: "codemod",
    remotePackage: true,
    apply:
      'Rewrite `color="primary"` to `color="default"` on `Breadcrumb`, `HeaderNavigation`, `Heading`, `IllustratedMessage`, and `Link` only — leave `Button` (and any other component where `"primary"` is still valid) untouched.',
  },
  {
    id: "table-cell-render-prop-removed",
    since: "0.2.0-alpha.846",
    title: "TableCell: `render` prop removed",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "Provide the cell content as children of `TableCell` instead of a `render` function.",
  },
  {
    id: "password-tools-rule",
    since: "0.2.0-alpha.802",
    title: "password-tools: `AsyncRule` and `SyncRule` replaced by `Rule`",
    kind: "migration",
    action: "codemod",
    remotePackage: false,
    apply:
      "Replace `AsyncRule` and `SyncRule` imports from `@mittwald/flow-react-components/mittwald-password-tools-js` with `Rule`. Update custom rule classes to extend `Rule` instead.",
  },
  {
    id: "accent-box-color-to-background-color",
    since: "0.2.0-alpha.786",
    title: "AccentBox.color is now a declaration for foreground",
    kind: "migration",
    action: "codemod",
    remotePackage: true,
    apply:
      'Move every `color` value that is not one of `"default" | "dark" | "light" | "dark-static" | "light-static"` to `backgroundColor` instead. Review `color={expression}` and any element that already has `backgroundColor` by hand — neither can be decided from the value alone.',
  },
  {
    id: "cartesian-chart-restructured",
    since: "0.2.0-alpha.780",
    title: "CartesianChart",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "Add `dataKeyLabel` wherever a `dataKey` is a function — a string `dataKey` already sets it automatically. Where a `tickFormatter` or other callback relied on the argument being `any`, add an explicit type check (for example `instanceof Date`), or switch to `typedCartesianChart<T>()` for a chart whose callbacks are typed from your own data shape.",
  },
  {
    id: "code-block-syntax-highlighter-removed",
    since: "0.2.0-alpha.756",
    title:
      "Removed the underlying react-syntax-highlighter library from CodeBlock",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "Check every `CodeBlock` usage against the current props (see the [CodeBlock documentation](https://flow.mittwald.de/04-components/content/code-block/overview)) and remove or replace props the new implementation does not support.",
  },
  {
    id: "muted-action-error-to-abort-action-error",
    since: "0.2.0-alpha.712",
    title: "`MutedActionError` renamed to `AbortActionError`",
    kind: "migration",
    action: "codemod",
    remotePackage: false,
    apply:
      'Rename `MutedActionError` to `AbortActionError`, `isMutedActionError` to `isAbortActionError`, and `rethrowIfNotMuted` to `rethrowIfNotAborted`. Update any `error.name === "MutedActionError"` comparison to `"AbortActionError"`.',
  },
  {
    id: "overlay-controller-add-on-close-return-type",
    since: "0.2.0-alpha.696",
    title: "OverlayController.addOnClose / addOnOpen return type changed",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "No type change needed: the return type widened from `() => void` to `() => unknown`, and a `() => void` callback stays assignable. Instead, check every callback passed to `addOnClose`/`addOnOpen` for one that can return `false` — for example an arrow function whose body is an expression evaluating to `false`. `executeHandlers` now treats any handler returning `false` as a veto and cancels the close/open. A callback that returned `false` incidentally, with no intent to block anything, now silently cancels closes.",
  },
  {
    id: "form-resets-after-modal-close",
    since: "0.2.0-alpha.694",
    title: "Form: resets itself after the surrounding modal closes",
    kind: "migration",
    action: "none",
    remotePackage: false,
    apply:
      "No code change required. To keep the previous behaviour (the form keeping what the user entered), pass `autoReset={false}` (or `autoReset={{ onAfterModalClose: false }}`) to `Form`.",
  },
  {
    id: "cartesian-chart-empty-view",
    since: "0.2.0-alpha.676",
    title: "CartesianChart.emptyView changed",
    kind: "migration",
    action: "manual",
    remotePackage: true,
    apply:
      "Wrap the `emptyView` value in JSX — `emptyView={<EmptyState />}` instead of `emptyView={EmptyState}`.",
  },
  {
    id: "action-prop-to-on-action",
    since: "0.2.0-alpha.646",
    title: "Action: `action` renamed to `onAction`",
    kind: "migration",
    action: "codemod",
    remotePackage: true,
    apply: "Rename the `action` prop on `Action` to `onAction`.",
  },
  {
    id: "button-props-interfaces",
    since: "0.2.0-alpha.646",
    title: "Removed ResetButton and SubmitButton Interfaces",
    kind: "migration",
    action: "codemod",
    remotePackage: false,
    apply:
      "Replace `ResetButtonProps`/`SubmitButtonProps` imports from `@mittwald/flow-react-components/react-hook-form` with `ButtonProps` from the package root. Leave `RemoteButtonElementProps` (from `@mittwald/flow-remote-elements`) alone.",
  },
  {
    id: "imports-to-package-root",
    since: "0.2.0-alpha.28",
    title: "Subpath imports moved to the package root",
    kind: "migration",
    action: "codemod",
    remotePackage: false,
    apply:
      'Rewrite every subdirectory import from `@mittwald/flow-react-components` to the package root, except `react-hook-form` and `nextjs`, which move to `@mittwald/flow-react-components/react-hook-form` and `@mittwald/flow-react-components/nextjs`. If you hit missing module errors, set `"module": "esnext"` in `tsconfig.json`.',
  },
  {
    id: "renamed-css-export",
    since: "0.1.0-alpha.292",
    title: "Renamed CSS export",
    kind: "migration",
    action: "manual",
    remotePackage: false,
    apply:
      "Replace the import `@mittwald/flow-react-components/styles` with `@mittwald/flow-react-components/all.css`.",
  },
];
