// This file is auto-generated by dev/status-registry/generateStatusRegistry.ts.
// Do not edit it by hand — regenerate with `pnpm nx build:status-registry components`.
import componentStatus from "./component-status.json";
import type {
  FlowComponentStatus,
  FlowComponentStatusRegistry,
  FlowExportEntry,
} from "./types";

export const flowComponentStatus =
  componentStatus as FlowComponentStatusRegistry;

const SPECIFIER_BY_ENTRY: Record<FlowExportEntry, string> = {
  ".": "@mittwald/flow-react-components",
  "flr-universal": "@mittwald/flow-react-components/flr-universal",
  nextjs: "@mittwald/flow-react-components/nextjs",
  "react-hook-form": "@mittwald/flow-react-components/react-hook-form",
  "password-tools": "@mittwald/flow-react-components/password-tools",
};

/**
 * Looks up a component's lifecycle status on a given public export surface.
 * `entry` defaults to the main `.` surface. Returns `undefined` when the
 * component has no derivable status on that surface (consumers fail silently).
 */
export const getFlowComponentStatus = (
  name: string,
  entry: FlowExportEntry = ".",
): FlowComponentStatus | undefined =>
  flowComponentStatus[`${SPECIFIER_BY_ENTRY[entry]}#${name}`];
