// This file is auto-generated by dev/status-registry/generateStatusRegistry.ts.
// Do not edit it by hand — regenerate with `pnpm nx build:status-registry components`.
import componentStatus from "./component-status.json";
import type { FlowComponentStatus, FlowComponentStatusRegistry } from "./types";

export const flowComponentStatus =
  componentStatus as FlowComponentStatusRegistry;

export const getFlowComponentStatus = (
  displayName: string,
): FlowComponentStatus | undefined => flowComponentStatus[displayName];
