// This file is auto-generated by dev/status-registry/generateStatusRegistry.ts.
// Do not edit it by hand — regenerate with `pnpm nx build:status-registry components`.
import componentStatus from "./component-status.json";
import type { FlowComponentStatus, FlowComponentStatusRegistry } from "./types";

export const flowComponentStatus =
  componentStatus as FlowComponentStatusRegistry;

/**
 * The component-bearing public export entries — generated from
 * `STATUS_EXPORT_ENTRIES` (dev/status-registry/exportEntries.ts).
 */
export type FlowExportEntry =
  | "."
  | "flr-universal"
  | "nextjs"
  | "react-hook-form"
  | "mittwald-password-tools-js";

const PACKAGE_NAME = "@mittwald/flow-react-components";

/**
 * The public import specifier for an export entry (mirrors specifierOf in
 * exportEntries.ts).
 */
const specifierOf = (entry: FlowExportEntry): string =>
  entry === "." ? PACKAGE_NAME : `${PACKAGE_NAME}/${entry}`;

/**
 * Looks up a component's lifecycle status on a given public export surface.
 * `entry` defaults to the main `.` surface. Returns `undefined` when the
 * component has no derivable status on that surface (consumers fail silently).
 */
export const getFlowComponentStatus = (
  name: string,
  entry: FlowExportEntry = ".",
): FlowComponentStatus | undefined =>
  flowComponentStatus[`${specifierOf(entry)}#${name}`];
