import * as fsSync from "fs";
import * as fs from "fs/promises";
import path from "path";

import type { ComponentDoc } from "react-docgen-typescript";
import {
  buildStatusRegistry,
  type DerivedStatusRegistry,
  type StatusRegistryEntry,
} from "./buildStatusRegistry";
import { STATUS_EXPORT_ENTRIES, specifierOf } from "./exportEntries";
import { parsePublicComponentNames } from "./parsePublicComponentNames";
import { parseFlrUniversalComponentNames } from "./parseFlrUniversalComponentNames";
import { parseIntegrationIndexComponentNames } from "./parseIntegrationIndexComponentNames";

const DOC_PROPERTIES_FILE = "./dist/assets/doc-properties.json";
const PACKAGE_JSON_FILE = "./package.json";
const STATUS_DIR = "./src/status";
const JSON_FILE = path.join(STATUS_DIR, "component-status.json");
const WRAPPER_FILE = path.join(STATUS_DIR, "componentStatus.ts");

// Must stay in sync with `FlowComponentStatusLevel` (src/status/types.ts) and
// `DerivedComponentStatusLevel` (deriveComponentStatus.ts) — see the guard below.
const ALLOWED_LEVELS = ["beta", "stable", "deprecated"] as const;

/** Short `FlowExportEntry` token for an export key: `.` stays `.`, `./x` → `x`. */
const entryTokenOf = (key: string): string =>
  key === "." ? "." : key.slice(2);

/**
 * Re-sorts the registry by plain string comparison to match the repo's
 * `prettier-plugin-sort-json` (all uppercase-led keys before any lowercase-led
 * key), keeping the written file byte-identical to a lint pass.
 */
const sortForJson = (registry: DerivedStatusRegistry): DerivedStatusRegistry =>
  Object.fromEntries(
    Object.entries(registry).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  );

/**
 * Renders an object key the way `quoteProps: "as-needed"` (this repo's prettier
 * config) would: unquoted when the key is a valid JS identifier, quoted
 * otherwise (e.g. `.`, `react-hook-form`). Keeps the generated wrapper
 * byte-identical to a lint pass.
 */
const renderKey = (key: string): string =>
  /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : `"${key}"`;

const buildWrapperSource = (
  specifierByEntry: Record<string, string>,
): string => {
  const entries = Object.entries(specifierByEntry)
    .map(([token, specifier]) => `  ${renderKey(token)}: "${specifier}",`)
    .join("\n");

  return `// This file is auto-generated by dev/status-registry/generateStatusRegistry.ts.
// Do not edit it by hand — regenerate with \`pnpm nx build:status-registry components\`.
import componentStatus from "./component-status.json";
import type {
  FlowComponentStatus,
  FlowComponentStatusRegistry,
  FlowExportEntry,
} from "./types";

export const flowComponentStatus =
  componentStatus as FlowComponentStatusRegistry;

const SPECIFIER_BY_ENTRY: Record<FlowExportEntry, string> = {
${entries}
};

/**
 * Looks up a component's lifecycle status on a given public export surface.
 * \`entry\` defaults to the main \`.\` surface. Returns \`undefined\` when the
 * component has no derivable status on that surface (consumers fail silently).
 */
export const getFlowComponentStatus = (
  name: string,
  entry: FlowExportEntry = ".",
): FlowComponentStatus | undefined =>
  flowComponentStatus[\`\${SPECIFIER_BY_ENTRY[entry]}#\${name}\`];
`;
};

function collectEntryComponents(
  key: string,
  source: string,
  sourceRoot: string,
): StatusRegistryEntry["components"] {
  if (key === ".") {
    return [...parsePublicComponentNames(source)].map((name) => ({
      name,
      sourceRoot,
    }));
  }
  if (key === "./flr-universal") {
    return [...parseFlrUniversalComponentNames(source)].map((name) => ({
      name,
      sourceRoot,
    }));
  }
  return parseIntegrationIndexComponentNames(source, sourceRoot);
}

async function generateStatusRegistry() {
  console.log("📚 Reading " + path.resolve(DOC_PROPERTIES_FILE));
  const components = JSON.parse(
    await fs.readFile(DOC_PROPERTIES_FILE, "utf-8"),
  ) as ComponentDoc[];

  const packageName = (
    JSON.parse(await fs.readFile(PACKAGE_JSON_FILE, "utf-8")) as {
      name: string;
    }
  ).name;

  const entries: StatusRegistryEntry[] = [];
  const specifierByEntry: Record<string, string> = {};

  for (const entry of STATUS_EXPORT_ENTRIES) {
    const specifier = specifierOf(entry.key, packageName);
    specifierByEntry[entryTokenOf(entry.key)] = specifier;

    const source = await fs.readFile(`./${entry.indexFile}`, "utf-8");
    const entryComponents = collectEntryComponents(
      entry.key,
      source,
      entry.sourceRoot,
    );
    if (entryComponents.length === 0) {
      throw new Error(
        `Export entry "${entry.key}" resolved to zero component names — ` +
          `check the parser against ${entry.indexFile}.`,
      );
    }
    entries.push({ specifier, components: entryComponents });
  }

  console.log("🧮 Building status registry");
  const unsortedRegistry = buildStatusRegistry(components, entries);

  for (const [key, status] of Object.entries(unsortedRegistry)) {
    if (
      !ALLOWED_LEVELS.includes(status.level as (typeof ALLOWED_LEVELS)[number])
    ) {
      throw new Error(`Unknown status level "${status.level}" for "${key}".`);
    }
  }

  const registry = sortForJson(unsortedRegistry);

  if (!fsSync.existsSync(STATUS_DIR)) {
    await fs.mkdir(STATUS_DIR, { recursive: true });
  }

  console.log("📝 Writing " + path.resolve(JSON_FILE));
  await fs.writeFile(JSON_FILE, JSON.stringify(registry, null, 2) + "\n");

  console.log("📝 Writing " + path.resolve(WRAPPER_FILE));
  await fs.writeFile(WRAPPER_FILE, buildWrapperSource(specifierByEntry));

  console.log(
    `✅  Done — ${Object.keys(registry).length} entries in the registry`,
  );
}

void generateStatusRegistry().catch((error) => {
  console.error("❌ Failed to generate the component status registry:");
  console.error(error instanceof Error ? error.message : error);
  console.error(
    "   Did you run `pnpm nx build:docs-properties components` first? " +
      "(dist/assets/doc-properties.json must exist)",
  );
  process.exitCode = 1;
});
