import * as fsSync from "fs";
import * as fs from "fs/promises";
import path from "path";

import type { ComponentDoc } from "react-docgen-typescript";
import {
  buildStatusRegistry,
  type DerivedStatusRegistry,
} from "./buildStatusRegistry";

const DOC_PROPERTIES_FILE = "./dist/assets/doc-properties.json";
const STATUS_DIR = "./src/status";
const JSON_FILE = path.join(STATUS_DIR, "component-status.json");
const WRAPPER_FILE = path.join(STATUS_DIR, "componentStatus.ts");

const WRAPPER_SOURCE = `// This file is auto-generated by dev/status-registry/generateStatusRegistry.ts.
// Do not edit it by hand — regenerate with \`pnpm nx build:status-registry components\`.
import componentStatus from "./component-status.json";
import type { FlowComponentStatus, FlowComponentStatusRegistry } from "./types";

export const flowComponentStatus =
  componentStatus as FlowComponentStatusRegistry;

export const getFlowComponentStatus = (
  displayName: string,
): FlowComponentStatus | undefined => flowComponentStatus[displayName];
`;

/**
 * Re-sorts the registry by plain string comparison. `buildStatusRegistry` sorts
 * with `localeCompare` (interleaving upper/lower case alphabetically); the
 * repo's `prettier-plugin-sort-json` sorts JSON object keys by plain comparison
 * instead (all uppercase-led keys before any lowercase-led key). Matching that
 * order here keeps the written file byte-identical to what a lint pass would
 * produce, so regenerating yields no diff.
 */
const sortForJson = (registry: DerivedStatusRegistry): DerivedStatusRegistry =>
  Object.fromEntries(
    Object.entries(registry).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)),
  );

async function generateStatusRegistry() {
  console.log("📚 Reading " + path.resolve(DOC_PROPERTIES_FILE));
  const raw = await fs.readFile(DOC_PROPERTIES_FILE, "utf-8");
  const components = JSON.parse(raw) as ComponentDoc[];

  console.log("🧮 Building status registry");
  const registry = sortForJson(buildStatusRegistry(components));

  if (!fsSync.existsSync(STATUS_DIR)) {
    await fs.mkdir(STATUS_DIR, { recursive: true });
  }

  console.log("📝 Writing " + path.resolve(JSON_FILE));
  await fs.writeFile(JSON_FILE, JSON.stringify(registry, null, 2) + "\n");

  console.log("📝 Writing " + path.resolve(WRAPPER_FILE));
  await fs.writeFile(WRAPPER_FILE, WRAPPER_SOURCE);

  console.log(
    `✅  Done — ${Object.keys(registry).length} components in the registry`,
  );
}

void generateStatusRegistry();
