/**
 * Bundles every composite in `src/composites` into a self-contained transform
 * in `src/transforms`.
 *
 * Consumers run a codemod straight from GitHub:
 *
 * ```shell
 * npx jscodeshift -t https://raw.githubusercontent.com/.../<name>.ts --parser tsx src
 * ```
 *
 * That URL is downloaded into a file in the OS temp dir and required from
 * there. Relative imports then resolve against the temp dir, where no sibling
 * file exists — so a transform served by URL must not have any. A composite
 * that runs several transforms in one pass needs them, which is what this
 * generator resolves: it inlines each imported transform into a single file
 * that runs standalone.
 *
 * The generator is deliberately strict. It understands exactly the shape every
 * transform in this package has — one type-only `jscodeshift` import, one
 * top-level declaration, one `export default <identifier>` — and throws on
 * anything else instead of emitting a bundle that silently drops code.
 */
import { readdir, readFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { fileURLToPath } from "node:url";
import jscodeshift from "jscodeshift";
import { format, resolveConfig } from "prettier";

const packageRoot = fileURLToPath(new URL("..", import.meta.url));
const compositesDir = join(packageRoot, "src", "composites");
const transformsDir = join(packageRoot, "src", "transforms");

const typeImportSource = "jscodeshift";
const transformImportPrefix = "../transforms/";

const j = jscodeshift.withParser("ts");

interface ParsedModule {
  /** Local name -> transform module name, for `import x from "../transforms/x"`. */
  transformImports: Map<string, string>;
  /** Identifier of the `export default <identifier>` declaration. */
  defaultExport: string;
  /** Everything except the imports and the default export, as source. */
  body: string;
}

// A function declaration, not an arrow: only that form narrows control flow
// after the call, so the checks below do not need a redundant `throw`.
function fail(file: string, message: string): never {
  throw new Error(`${basename(file)}: ${message}`);
}

const parseModule = (file: string, source: string): ParsedModule => {
  const root = j(source);
  const transformImports = new Map<string, string>();

  root.find(j.ImportDeclaration).forEach((path) => {
    const importSource = String(path.node.source.value);

    // `import type { Transform } from "jscodeshift"` — hoisted into the bundle
    // once, so it is dropped here.
    if (importSource === typeImportSource) {
      if (path.node.importKind !== "type") {
        fail(file, `imports "${typeImportSource}" at runtime, not as a type`);
      }
      return;
    }

    if (!importSource.startsWith(transformImportPrefix)) {
      fail(file, `imports "${importSource}", which the bundler cannot inline`);
    }

    const specifiers = path.node.specifiers ?? [];
    const [specifier] = specifiers;
    if (
      specifiers.length !== 1 ||
      specifier?.type !== "ImportDefaultSpecifier"
    ) {
      fail(file, `imports "${importSource}" with a non-default specifier`);
    }

    transformImports.set(
      String(specifier.local?.name),
      importSource.slice(transformImportPrefix.length),
    );
  });

  const defaultExports = root.find(j.ExportDefaultDeclaration);
  if (defaultExports.length !== 1) {
    fail(file, `has ${defaultExports.length} default exports, expected 1`);
  }

  const exported = defaultExports.nodes()[0]?.declaration;
  if (!exported || exported.type !== "Identifier") {
    fail(file, "does not export an identifier as its default");
  }
  const defaultExport = String(exported.name);

  root.find(j.ImportDeclaration).remove();
  defaultExports.remove();

  return { transformImports, defaultExport, body: root.toSource().trim() };
};

const buildBundle = async (compositeFile: string): Promise<string> => {
  const composite = parseModule(
    compositeFile,
    await readFile(compositeFile, "utf8"),
  );

  const inlined: string[] = [];

  for (const [localName, moduleName] of composite.transformImports) {
    const transformFile = join(transformsDir, `${moduleName}.ts`);
    const transform = parseModule(
      transformFile,
      await readFile(transformFile, "utf8"),
    );

    if (transform.transformImports.size > 0) {
      fail(transformFile, "imports another transform, which is not supported");
    }

    inlined.push(transform.body);
    // The composite refers to the imported binding, the inlined body declares
    // the transform under its own name — this bridges the two.
    if (localName !== transform.defaultExport) {
      inlined.push(`const ${localName} = ${transform.defaultExport};`);
    }
  }

  const header = [
    `// AUTO-GENERATED by \`pnpm nx build codemods\` — do not edit.`,
    `//`,
    `// Source: packages/codemods/src/composites/${basename(compositeFile)}`,
    `//`,
    `// jscodeshift downloads a \`-t <url>\` transform into the OS temp dir and`,
    `// requires it from there, so a transform served by URL cannot have relative`,
    `// imports. This is the composite above with its transforms inlined.`,
  ].join("\n");

  const bundle = [
    header,
    `import type { Transform } from "${typeImportSource}";`,
    ...inlined,
    composite.body,
    `export default ${composite.defaultExport};`,
  ].join("\n\n");

  const prettierConfig = await resolveConfig(compositeFile);
  return format(bundle, { ...prettierConfig, parser: "typescript" });
};

/** File names of every composite, e.g. `["flow1.ts"]`. */
export const listComposites = async (): Promise<string[]> =>
  (await readdir(compositesDir)).filter((file) => file.endsWith(".ts")).sort();

/** The bundle a composite file name should produce, as source. */
export const bundleComposite = (file: string): Promise<string> =>
  buildBundle(join(compositesDir, file));

/** The bundle currently committed for a composite file name. */
export const readBundledTransform = (file: string): Promise<string> =>
  readFile(join(transformsDir, file), "utf8");
