name: "Generate coverage badges"
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  generate-jest-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - run: yarn install --immutable
      - uses: nrwl/nx-set-shas@v4

      - name: Delete remote badges branch
        run: git push origin --delete badges

      - name: Create badges branch
        run: git checkout -b badges

      - name: Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test:unit --ci --json --coverage --testLocationInResults --outputFile=report.json
          dir: packages/components

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          target-branch: badges
          coverage-summary-path: ./packages/components/coverage/coverage-summary.json

      - name: Push badges branch
        run: git push origin badges