name: "Build test coverage report"

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile

      - name: Test components
        run: pnpm nx test:unit components --coverage.enabled true

      - name: Report Coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: ./packages/components/
